### ISSUE TITLE
官网打不开

### ISSUE THREAD

**Issue by he426100** [YanxinNet/uView#10]

**Comment by anihCevol** [comment]
由于uView今天持续受到DDos攻击，导致服务器宕机，腾讯又已“安全”为由要买高额的高防包才解封IP，所以uView将官网部署到了Gitee。 
我们会向着风，拥抱彩虹，勇敢的向前走，透过黎明的那道光，越过黑暗，打破一切恐惧，我能找到答案，哪怕要逆着光，也要驱散黑暗。
