### ISSUE TITLE
icon图标可否再丰富一下

### ISSUE THREAD

**Issue by YongHangPu** [YanxinNet/uView#102]
UView是个很棒的UI框架,我相信以后会成为像Element那样的存在,作者加油;
原因,想用一个删除图标未找到

**Comment by Adgeros** [comment]
可自定义扩展

**Comment by YanxinNet** [comment]
有trash-fill和trash图标(垃圾桶)，也有叉号的图标，如果还不满足个性化要求，有两个途径：

1.  在1.3.0版本中，"Icon"组件可以传入图片，同小图标替代。
2. 通过扩展自定义图标库的形式集成自己想要的图标，详见：
https://www.uviewui.com/components/customIcon.html

**Comment by Adgeros** [comment]
> 有trash-fill和trash图标(垃圾桶)，也有叉号的图标，如果还不满足个性化要求，有两个途径：
> 
> 1. 在1.3.0版本中，"Icon"组件可以传入图片，同小图标替代。
> 2. 通过扩展自定义图标库的形式集成自己想要的图标，详见：
>    https://www.uviewui.com/components/customIcon.html

文档上没有显示出来
