### ISSUE TITLE
自定义导航栏返回事件custom-back拿不到this

### ISSUE THREAD

**Issue by ILfengzi** [YanxinNet/uView#1057]
自定义导航栏返回事件custom-back拿不到this，拿到 this 的值为false

**Comment by ILfengzi** [comment]
已解决：将相应组件的源代码232行改为以下方法，感觉官方封装的$u有bug
![image](https://user-images.githubusercontent.com/48777137/127611532-ff55f424-bd26-4e51-94ab-885e61705955.png)

**Comment by zhangzhuang15** [comment]
请问，这个是在 u-navbar源码去修改嘛？ @ILfengzi

**Comment by ILfengzi** [comment]
已收到！

**Comment by zhangzhuang15** [comment]
你好 ，您发给我的邮件我已经收到。
