### ISSUE TITLE
read-more 组件说明有问题

### ISSUE THREAD

**Issue by xuyongbao** [YanxinNet/uView#106]
![image](https://user-images.githubusercontent.com/17819284/84115354-86995700-aa60-11ea-9ba3-f6619fbdb5de.png)
showHeight 说是rpx，但是实际代码中是用的px；
`
style="{ height: isLongContent && !showMore ? showHeight + 'px' : 'auto' }"
`
应该使用rpx，因为实际开发中都用rpx作为单位，这里突然来个px不太方便
`
	query
	.select('.u-content')
        .boundingClientRect(res => {
	  if (res) {
	  // 判断高度，如果真实内容高度大于占位高度，则显示收起与展开的控制按钮
	    if (res.height > this.showHeight) {
	      this.isLongContent = true;
	      this.showMore = false;
	    }
	  }
	})
	.exec();
`
这里的高度判断if 可以写成转化下 res.height / 手机屏幕宽度 * 750 就是rpx了，上面就可以用rpx

**Comment by BeiQiaoT** [comment]
> ![image](https://user-images.githubusercontent.com/17819284/84115354-86995700-aa60-11ea-9ba3-f6619fbdb5de.png)
> showHeight 说是rpx，但是实际代码中是用的px；
> `style="{ height: isLongContent && !showMore ? showHeight + 'px' : 'auto' }"`
> 应该使用rpx，因为实际开发中都用rpx作为单位，这里突然来个px不太方便
> `query .select('.u-content') .boundingClientRect(res => { if (res) { // 判断高度，如果真实内容高度大于占位高度，则显示收起与展开的控制按钮 if (res.height > this.showHeight) { this.isLongContent = true; this.showMore = false; } } }) .exec();`
> 这里的高度判断if 可以写成转化下 res.height / 手机屏幕宽度 * 750 就是rpx了，上面就可以用rpx

刚看了下源码，发现的确是这样。

**Comment by YanxinNet** [comment]
1.3.3版本已处理此问题，感谢反馈
