### ISSUE TITLE
[优化]tabbar编译成app首次切换页面会闪现，有了缓存后不闪现。原生无此现象

### ISSUE THREAD

**Issue by Gambler-Wang** [YanxinNet/uView#1062]
组件很棒，关键是很用心。第一次使用uniapp，选用了uview做基础UI组件进行开发，总之很赞。

在开发项目中，因为原生的tabbar无法引入svg，png毛刺较大，所以想使用这款自定义组件。使用官方demo替换svg可以，但同时发现存在这样的问题，使用Tabbar后，首次切换页面，在手机上会存在闪现的状态，后面可能有缓存就没有了，其次适配上有些瑕疵。

**Comment by tttao7** [comment]
闪屏问题是uniapp官方的问题，如需解决只能通过原生导航栏处理。
