### ISSUE TITLE
1.3.0 navbar back会返回两层

### ISSUE THREAD

**Issue by arhularm** [YanxinNet/uView#108]
is-back=true以后，点击会返回2层，应该view和icon都加了tap事件导致的。源码里去掉icon的click事件以后正常。
![navbug](https://user-images.githubusercontent.com/39142535/84126012-f06d2d00-aa6f-11ea-98a3-aeb1cb5c9102.png)

**Comment by BeiQiaoT** [comment]
> is-back=true以后，点击会返回2层，应该view和icon都加了tap事件导致的。源码里去掉icon的click事件以后正常。
> ![navbug](https://user-images.githubusercontent.com/39142535/84126012-f06d2d00-aa6f-11ea-98a3-aeb1cb5c9102.png)

好的，收到

**Comment by YanxinNet** [comment]
1.3.2已处理此问题，感谢反馈
