### ISSUE TITLE
u-collapse-item怎么在代码里控制展开或者关闭

### ISSUE THREAD

**Issue by lucky51** [YanxinNet/uView#1082]
u-collapse-item怎么在代码里控制展开或者关闭

<u-collapse-item title="点击查看解析" :open="openAnswerPanel" ></u-collapse-item>
这个open只对初始化有用 ，之后在修改这个值，也不会有变化。
怎么在代码里边 ，控制打开或者关闭。
难道只能手点嘛？

**Comment by liwenfengg** [comment]
你好,这个问题你解决了吗

**Comment by lucky51** [comment]
> 你好,这个问题你解决了吗

解决了
