### ISSUE TITLE
swiper组件list参数，数组长度发生变化，图片显示不出

### ISSUE THREAD

**Issue by hope-11** [YanxinNet/uView#11]
小程序中swiper组件list参数，数组长度发生变化，图片显示不出，拖动的时候会出错

VM4497:1 TypeError: Cannot read property '$$' of undefined
    at HTMLElement._attached.wx.getPlatform._touchstartHandlerForDevtools

**Comment by hope-11** [comment]
swiper的current值大于新的list数组长度导致的。。。请问在list发生改变时可以强制current=0吗？

**Comment by YanxinNet** [comment]
此问题经测试，无法重新，请加群艾特群主或者管理员，提供一个简单的demo供我们排查，群号：249718512
