### ISSUE TITLE
1.3.0 表单u-form错误信息无法拿到嘛？

### ISSUE THREAD

**Issue by fuyunmanbu** [YanxinNet/uView#110]
想弹个框都麻烦，或者也可以内置弹框，弹出错误信息。
![Snip20200609_7](https://user-images.githubusercontent.com/16368126/84134212-d4bb5400-aa7a-11ea-9226-d842bb642f03.png)

**Comment by YuXin888** [comment]
在移动端错误信息弹框真的很重要，目前在表单下方提示错误信息比较适合在Web端

**Comment by BeiQiaoT** [comment]
> 在移动端错误信息弹框真的很重要，目前在表单下方提示错误信息比较适合在Web端

如果一直弹窗的话，觉得那是个噩梦，表单下方只是在输入是给的实时验证现实哦

**Comment by fuyunmanbu** [comment]
![IMG_2449](https://user-images.githubusercontent.com/16368126/84151605-33da9200-aa96-11ea-88c0-79bde4b72999.PNG)
这种弹框小需求不常见？我看别的框架基本包含，而且我基本都是这么弹框提示的

**Comment by wangkaixuan0013** [comment]
1.3.5版本起form表单验证新增toast的错误提示方式，配置erroryType=['toast']即可
