### ISSUE TITLE
在main.js引入后报错ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by DuanxxPlus** [YanxinNet/uView#111]
![image](https://user-images.githubusercontent.com/46832413/84134835-c0c42200-aa7b-11ea-8de8-09f401985b69.png)
如图
mai.js↓
![image](https://user-images.githubusercontent.com/46832413/84134929-df2a1d80-aa7b-11ea-809d-66586912d591.png)

**Comment by BeiQiaoT** [comment]
> ![image](https://user-images.githubusercontent.com/46832413/84134835-c0c42200-aa7b-11ea-8de8-09f401985b69.png)
> 如图
> mai.js↓
> ![image](https://user-images.githubusercontent.com/46832413/84134929-df2a1d80-aa7b-11ea-809d-66586912d591.png)

对照图文教程来一遍试试https://blog.csdn.net/qq_33162604/article/details/105996312
