### ISSUE TITLE
u-action-sheet文档全是错的？

### ISSUE THREAD

**Issue by pscj** [YanxinNet/uView#1114]
文档里属性全是错的没法用

demo里  `<u-action-sheet :list="list"v-model="show"></u-action-sheet>`  能正常弹出
文档里  `<u-action-sheet :actions="list" :show="show">`  不能弹出。
文档在这里 https://www.uviewui.com/components/actionSheet.html

**Comment by nadirvishun** [comment]
文档中并没有看到`<u-action-sheet :actions="list" :show="show">`这句话啊，你从哪里弄出来的？

**Comment by pscj** [comment]
现在看着是正常了，难道昨天是眼花了，汗
