### ISSUE TITLE
collapse组件内置init方法, 当多次调用init方法后, childrens数组的长度会成2倍数增长, 并没有每次重置

### ISSUE THREAD

**Issue by mofle07** [YanxinNet/uView#1127]
![u-view组件-u-collapse组件](https://user-images.githubusercontent.com/42170476/134474508-701299b5-f80b-40a4-8985-85990c1c8593.png)

**Comment by light1644588** [comment]
可以修改init方法，init主要实现的交互效果是是重新计算折叠高度的方法【queryRect】源码如下
![image](https://user-images.githubusercontent.com/66264271/184086577-43802a16-d650-47ae-a7d7-e2ea149aa393.png)
去u-collapse文件里面重新写一个自定义名字的方法就可以了。如下：
![image](https://user-images.githubusercontent.com/66264271/184086975-0f4bd962-5e48-4971-94cb-9c20cefdbb46.png)
