### ISSUE TITLE
[H5] u-search 在iOS15下两个搜索图标问题

### ISSUE THREAD

**Issue by suchenglin2017** [YanxinNet/uView#1135]
如下图出现两个搜索图标，文字错位。
官网的例子，iPhone11，iOS15下出现此问题。

![IMG_0249](https://user-images.githubusercontent.com/28212171/135246156-aa87f40b-9a15-4947-9dd5-5e2de41a7281.PNG)

**Comment by suchenglin2017** [comment]
**解决方案：**
升级uniapp到最新版本。

**Comment by 13725102796** [comment]
这个问题的原因是官方 input 组件 confirm-type 属性引起的。在某些原因上，多了个icon。我的临时处理方案是直接把这个confirm-type 属性删了，这样只是软键盘的文字 搜索 变成了 完成。
