### ISSUE TITLE
BUG: http模块中使用正则对URL验证问题

### ISSUE THREAD

**Issue by 2460392754** [YanxinNet/uView#130]
目前对`URL`最后的路径正则判断出现问题(最后一个`/`字符之后的字符路径)，无法正确判断大写的字符

[uView url正则函数](https://github.com/YanxinNet/uView/blob/master/uview-ui/libs/function/test.js#L15-L21)

例如:
```js
const url = 'http://localhost:8080/jeecg-boot/weixin/site/searchSiteById'

// 使用uview-ui/lib/function/test.js 文件中的url function
console.log(validate.url(url)) // false
```

**Comment by 2460392754** [comment]
判断错误，就会给完整的`URL`地址前面添加`/`

**Comment by YanxinNet** [comment]
1.3.4版本已修复此问题，感谢反馈。
