### ISSUE TITLE
BUG 官方文档对应图标显示错误

### ISSUE THREAD

**Issue by gp3098** [YanxinNet/uView#131]
### 所在页面
[向下箭头](https://uviewui.com/components/icon.html#%E5%9B%BE%E6%A0%87%E9%9B%86)
### 错误图标
arrow-down-fill

**Comment by wangkaixuan0013** [comment]
已确认,正在排查错误原因,不影响icon组件的正常使用,可通过官网右侧的演示页面查看实际图标样式

**Comment by wangkaixuan0013** [comment]
此问题已修复,感谢您的反馈
