### ISSUE TITLE
步进器的两个BUG能解决吗？

### ISSUE THREAD

**Issue by G-Alan** [YanxinNet/uView#143]
1.按钮改变步进器的value后，并没有改变双向绑定的value初始值
2.每次value值从1变为0时会自动弹回1，无法改变成0

**Comment by wangkaixuan0013** [comment]
建议您去更新成最新版本再测试一下,uview已经在1.3.3版本中将numberBox步进器改为使用v-model进行双向绑定

**Comment by paul-xiao** [comment]
请确认一下,   "uview-ui": "^1.5.4" 也没法动态改变 inputVal 

`
this.value = 10
// inputVal 没有改变

//u-number-box.vue
created() {
	this.inputVal = Number(this.value); //只初始化了 this.value, 如果this.value 主动改变没看到哪在修改this.inputVal
}		
`

**Comment by paul-xiao** [comment]
> 建议您去更新成最新版本再测试一下,uview已经在1.3.3版本中将numberBox步进器改为使用v-model进行双向绑定

请确认一下, "uview-ui": "^1.5.4" 也没法动态改变 inputVal

`
this.value = 10
// inputVal 没有改变

//u-number-box.vue
created() {
this.inputVal = Number(this.value); //只初始化了 this.value, 如果this.value 主动改变没看到哪在修改this.inputVal
}
`
