### ISSUE TITLE
slider组件在modal弹框里面无法使用，

### ISSUE THREAD

**Issue by AlwaysLoveme** [YanxinNet/uView#146]
如题，有业务需求需要在弹框里面使用滑动组件，但是一直无法滑动，经检查发现是，modal打开的时候，slider还获取不到元素，望修复此问题

**Comment by shunichio** [comment]
遇到同样的问题，请问有解决吗？

**Comment by wangkaixuan0013** [comment]
目前没有太好的解决方案,只能是在slider组件上添加v-if与弹窗进行同步绑定,弹窗弹出后再加载slider组件,后续我们会想办法对这个问题进行优化

**Comment by xiaolin0088** [comment]
略坑,不过vif可以解决
