### ISSUE TITLE
input 组件 type="password"  :password-icon="false" 下输入是明文！！！

### ISSUE THREAD

**Issue by softtearsmile** [YanxinNet/uView#151]
:password-icon="false" 是去除右边眼睛icon，不进行切换
怎么结果连输入都变成明文了！

这是input组件的源码 
`
...
showPassword: this.passwordIcon, // 是否预览密码
...
`
showPassword:true 时密文；反之 false 时明文，所以在 showPassword:this.passwordIcon 这里明显有问题！

但在官方示例上 添加 :password-icon="false"，依旧是密文，而且input源码在这方面部分是一样的(只针对 showPassword 和 passwordIcon )，这又很神奇！反正我是蒙了。

**Comment by wangkaixuan0013** [comment]
此问题正在处理,下一版本将修复此问题

**Comment by wangkaixuan0013** [comment]
1.3.6版本已修复此问题
