### ISSUE TITLE
VM108:1 jsEnginScriptError Component is not found in path "uview-ui/components/u-swiper/u-swiper" (using by "pages/index/index");onAppRoute Error: Component is not found in path "uview-ui/components/u-swiper/u-swiper" (using by "pages/index/index")

### ISSUE THREAD

**Issue by Ya-hui** [YanxinNet/uView#160]
VM108:1 jsEnginScriptError
Component is not found in path "uview-ui/components/u-swiper/u-swiper" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "uview-ui/components/u-swiper/u-swiper" (using by "pages/index/index")

报错信息如上， 其他组件都可正常使用 引入是没问题的

**Comment by tttao7** [comment]
> VM108:1 jsEnginScriptError
> Component is not found in path "uview-ui/components/u-swiper/u-swiper" (using by "pages/index/index");onAppRoute
> Error: Component is not found in path "uview-ui/components/u-swiper/u-swiper" (using by "pages/index/index")
> 
> 报错信息如上， 其他组件都可正常使用 引入是没问题的

这应该是配置问题 或者没有重新编译导致的，建议你多检查下，如果还是不行可以在群内提问。群号：249718512
