### ISSUE TITLE
官网示例 this.$u.queryParams(this.data, true, 'indices') 报错！

### ISSUE THREAD

**Issue by softtearsmile** [YanxinNet/uView#162]
这是有问题的文件路径
uView/uview-ui/libs/function/queryParams.js
以下是git上的源码
```js
case 'indices':
	// 结果: ids[0]=1&ids[1]=2&ids[2]=3
	for (i = 0; i < value.length; i++) {
		_result.push(key + '[' + i + ']=' + value[i])
	}
	break;
```
很明显的错误，没有声明 i ，本人本地测试 let i =0后，就变正常了；

UI库证明了作者强大的能力，虽然是个新生UI，但起码官网上的示例也得跑对吧！！！不然败路人缘了。

目前为止，uView使用感觉很愉快，希望作者砥砺前行。

**Comment by tttao7** [comment]
此问题已修复，感谢反馈。
