### ISSUE TITLE
Grid 宫格布局的边框无效果

### ISSUE THREAD

**Issue by jourdon** [YanxinNet/uView#166]
我直接把  pages/componentsC/grid/index.vue 里的内容都复制到本地调试，也是无效果。
然后发现边框用的是 
u-border-right u-border-bottom  u-border-top u-border-left
本地调试发现没有起作用
不知道是哪里的问题

**Comment by jourdon** [comment]
另外宫格的边框宽度如果可以定义就更好了

**Comment by DeathBrain** [comment]
> 另外宫格的边框宽度如果可以定义就更好了

兄弟解决了吗,是不是版本问题
