### ISSUE TITLE
uniapp-小程序端，升级为uview-ui 1.3.7，全局的box-sizing：borde-box;失效，导致布局混乱

### ISSUE THREAD

**Issue by Navi-1993** [YanxinNet/uView#172]
uniapp-小程序端，升级为uview-ui 1.3.7，全局的box-sizing：borde-box;失效，导致布局混乱，现已回退至1.3.6

**Comment by tttao7** [comment]
为了不让框架的样式干扰到用户的样式，所以我们取消了全局的`box-sizing：borde-box;`，建议您自己添加，感谢反馈。

**Comment by zhaoyunyes** [comment]
版本 1.6.5
uView的全局样式里面有box-sizing: border-box;

并且uView的组件依赖于这个全局样式
