### ISSUE TITLE
popup组件不支持默认显示

### ISSUE THREAD

**Issue by qinkaiyuan** [YanxinNet/uView#188]
`<u-popup v-model="showMoreList">`

showMoreList 初始值为true时，popup不显示。

只有将值从false改为true才能显示。

希望可以支持默认显示功能

**Comment by wangkaixuan0013** [comment]
以前旧的版本的hx是可以一开始就设置true的，到了2.6.16以后就不行了,如果您需要一进入页面就弹出组件，您可以在data中设置show为false，在onReady生命周期设置show为true即可。
