### ISSUE TITLE
请问AvatarCropper功能的裁剪页面找不到

### ISSUE THREAD

**Issue by chenbigcur** [YanxinNet/uView#190]
![123](https://user-images.githubusercontent.com/40688723/85993457-f8920a00-ba28-11ea-8b85-78f1edff37cc.png)
![234](https://user-images.githubusercontent.com/40688723/85993488-0182db80-ba29-11ea-8597-476ed748f5dd.png)
u-avatar-cropper这个页面不会自动打包的吗，是需要手动复制的吗

**Comment by wangkaixuan0013** [comment]
组件使用注意事项中有说明,如果是下载安装的方式,直接按照说明配置即可,由于HBX的限制,npm安装的需要将页面复制出来放到项目中再进行配置https://www.uviewui.com/components/avatarCropper.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
