### ISSUE TITLE
full-screen压窗屏组件设置透明背景色无效

### ISSUE THREAD

**Issue by chinaliuming123** [YanxinNet/uView#194]
full-screen压窗屏组件设置透明背景色无效，按照官方配置之后为白色，依然会覆盖掉上一页。

**Comment by qinkaiyuan** [comment]
我遇到过类似问题，是因为给page设置了背景色。可以看下是否有统一设置背景色。

**Comment by chinaliuming123** [comment]
> [页]可以看下是否有统一设置背景色。

统一设置背景色为透明没有作用，依然是白色的背景
