### ISSUE TITLE
[建议] 精简颜色样式类名称

### ISSUE THREAD

**Issue by qinkaiyuan** [YanxinNet/uView#195]
### uview 样式类名称

字体color
 ```
.u-type-error      .u-type-warning-disabled
```
背景background
 ```
.u-type-primary-bg
```

### vuetify 样式类名称

字体color
 ```
.text--green
```
背景background
 ```
.blue
```

### color-ui 样式类名称

字体color
 ```
.text-green
```
背景background
 ```
.bg-blue
```

相比其他两款 ui 框架， uview的样式类名称 有些略显烦琐 

建议可以修改为，  
```
u-error, u-success
u-error-bg, u-success-bg
```

或者
```
text-error,text-success
bg-error,bg-success
```

再或者
```
error-bg,
error-text
```

我更倾向于 

```
text-error, text-success
bg-error, bg-success
```

这种方式，在大家无法准确牢记各种颜色名称时，只需打出来  bg或者text后就可以靠 开发工具智能提示。

如果能采纳此建议，我可以负责开发此功能，就是改个名字的事。

**Comment by tttao7** [comment]
由于已经有很多伙伴使用，现在改会出现很多问题。我们将会在后期做一个更规范的方案，感谢您的建议。

**Comment by qinkaiyuan** [comment]
> 由于已经有很多伙伴使用，现在改会出现很多问题。我们将会在后期做一个更规范的方案，感谢您的建议。

是否可以在不修改原代码的基础上增加样式类

**Comment by tttao7** [comment]
我们后续会给您一个更好的方案哈，希望您继续支持，因为这个牵涉到很多东西，我们也会努力去做更规范。

**Comment by qinkaiyuan** [comment]
> 我们后续会给您一个更好的方案哈，希望您继续支持，因为这个牵涉到很多东西，我们也会努力去做更规范。

辛苦了

**Comment by tttao7** [comment]
感谢您的支持
