### ISSUE TITLE
如何获取webview页面的cookie(第三方页面)

### ISSUE THREAD

**Issue by chianz** [YanxinNet/uView#2]
你好，请教下使用uniapp如何获取嵌入的第三方webview页面的cookie，比如内嵌了百度网页，怎么获取webview里百度的cookie呢

**Comment by Tokinx** [comment]
理论上是无法获取到的，不同域下一般是禁止通信的。
另外请不要滥用issues，此类非uView相关问题建议前往uniapp官方论坛提问
