### ISSUE TITLE
网址为 https://h5.uviewui.com/#/pages/componentsB/swiper/index 的网页可能暂时无法连接，或者它已永久性地移动到了

### ISSUE THREAD

**Issue by 869374965** [YanxinNet/uView#20]
如题，网址为 https://h5.uviewui.com/#/pages/componentsB/swiper/index 的网页可能暂时无法连接，或者它已永久性地移动到了xxx

**Comment by BeiQiaoT** [comment]
> 如题，网址为 https://h5.uviewui.com/#/pages/componentsB/swiper/index 的网页可能暂时无法连接，或者它已永久性地移动到了xxx

前段时间官网遭遇ddos攻击，目前已经恢复
