### ISSUE TITLE
如果两个页面都有Sticky 组件，来回撤回的时候，会弹出bottom错误

### ISSUE THREAD

**Issue by bbzhengcheng** [YanxinNet/uView#21]
h5-nav-height这个属性惹的，困了几周了希望尽快解决~
index.umd.min.js?1c31:1 Uncaught TypeError: Cannot read property 'bottom' of null
    at o (index.umd.min.js?1c31:1)
    at eval (index.umd.min.js?1c31:1)
    at Array.forEach (<anonymous>)
    at IntersectionObserver.a.<computed>.IntersectionObserver.root (index.umd.min.js?1c31:1)
o @ index.umd.min.js?1c31:1
eval @ index.umd.min.js?1c31:1
a.<computed>.IntersectionObserver.root @ index.umd.min.js?1c31:1

**Comment by BeiQiaoT** [comment]
> h5-nav-height这个属性惹的，困了几周了希望尽快解决~
> index.umd.min.js?1c31:1 Uncaught TypeError: Cannot read property 'bottom' of null
> at o (index.umd.min.js?1c31:1)
> at eval (index.umd.min.js?1c31:1)
> at Array.forEach ()
> at IntersectionObserver.a..IntersectionObserver.root (index.umd.min.js?1c31:1)
> o @ index.umd.min.js?1c31:1
> eval @ index.umd.min.js?1c31:1
> a..IntersectionObserver.root @ index.umd.min.js?1c31:1

这个问题是只存在于h5吗？
