### ISSUE TITLE
安卓系统下使用弹出层Click方法找不到

### ISSUE THREAD

**Issue by thqy39** [YanxinNet/uView#22]
15:53:15.873 [Vue warn]: Invalid handler for event "click": got undefined 15:53:15.912 found in 15:53:15.954 ---> <UPopup> at F:/work/uview-app/node_modules/uview-ui/components/u-popup/u-popup.vue

**Comment by YanxinNet** [comment]
可以加我们的官方群，提供一个demo给我们定位原因，QQ群：1042987248
