### ISSUE TITLE
1.2.6版本NumberBox 步进器无法减到0

### ISSUE THREAD

**Issue by Tokinx** [YanxinNet/uView#23]
版本：1.2.6
组件：NumberBox
问题：无法通过+、-将数字减到0；1.2.5版本正常
原因：
1.2.6版判断为：let tmp = /(^\d+$)/.test(v1) && String(v1)[0] != 0;
1.2.5版本判断为：let tmp = /(^\d+$)/.test(v1) && value[0] != 0;

**Comment by Tokinx** [comment]
let tmp = /(^\d+$)/.test(v1) && (String(v1).length < 2 || String(v1)[0] != 0);
改成这样不置可否，判断下输入的值是1位数还是多位数应该行吧？
期待下个版本修复这个问题

**Comment by YanxinNet** [comment]
1.3.0已修正此问题，感谢反馈，欢迎更新新版本。
