### ISSUE TITLE
u-field 全部变成password了

### ISSUE THREAD

**Issue by qq1037305420** [YanxinNet/uView#236]
![image](https://user-images.githubusercontent.com/28857867/87219166-98d22200-c38b-11ea-9636-82a3053c25f9.png)

更新了新版本 所有输入框都变成密码了
没有用password属性，type有默认值 所以一直为true

**Comment by zhoushaoping19** [comment]
估计是工程师手抖，加了三目运算符

**Comment by wangkaixuan0013** [comment]
此问题已在1.5.1版本修复,更新版本即可
