### ISSUE TITLE
cli 引入uview 报错

### ISSUE THREAD

**Issue by jiahuibin** [YanxinNet/uView#240]
![image](https://user-images.githubusercontent.com/15648477/87381648-c3102380-c5c7-11ea-9268-f76b5317d540.png)

**Comment by wangkaixuan0013** [comment]
uni-app对于vue cli和npm的支持度不高,容易出现一些我们无法解释的问题,这个与uview无关,如果可以的话我们还是推荐使用下载安装的方式
