### ISSUE TITLE
收货地址示例没有用u-form，u-input

### ISSUE THREAD

**Issue by muziling** [YanxinNet/uView#242]
收货地址示例没有用u-form，u-input组件，而是用了uni-app自还的input组件，
自己的例子都不用自己的组件
u-picker组件不知道是不是必须配合input组件使用，直接在u-picker上写@tap弹不出选择器。
例子选择完地区，输入框没显示已选择的地区

**Comment by wangkaixuan0013** [comment]
收货地址的示例写的比较早,那个时候还没有u-form和u-input组件,后续我们会考虑更新一下示例的代码;
u-picker的使用请阅读文档中的使用说明或下载示例项目查看示例是如何使用的
