### ISSUE TITLE
u-picker开发工具上设置默认值回显正常，真机测试不正常

### ISSUE THREAD

**Issue by PingTouG** [YanxinNet/uView#247]
`
    <u-picker
      mode="time"
      v-model="timeVisible"
      default-time="2020-07"
      :params="{ year: true,month: true }"
      @confirm="handleDateConfirm"
    />
`
真机：ipone 6s plus

**Comment by PingTouG** [comment]
u-calendar也不能回显，我看源码好像都没有接收这个prop，不知道是什么原因

**Comment by cafehaus** [comment]
我在真机和开发工具里都不能回显，只能每次打开重新把 timeVisible 赋值给default-time
