### ISSUE TITLE
H5使用 u-sticky 吸顶组件报错，切换tab至别的页面时会报错

### ISSUE THREAD

**Issue by heureux-live** [YanxinNet/uView#252]
错误内容

![image](https://user-images.githubusercontent.com/17950115/87764943-c1559280-c849-11ea-88ee-1073f8b614ff.png)

![image](https://user-images.githubusercontent.com/17950115/87765781-d41c9700-c84a-11ea-8077-bba56b13bb2c.png)
![test](https://user-images.githubusercontent.com/17950115/87766044-2b226c00-c84b-11ea-9c89-dac42a1177cf.gif)
官网的demo中也会报这个错误

**Comment by tttao7** [comment]
#239

**Comment by tttao7** [comment]
此问题暂不影响使用 我们也在定位这个问题 感谢反馈
