### ISSUE TITLE
vuecli 创建项目引入报错  

### ISSUE THREAD

**Issue by smart-shore** [YanxinNet/uView#254]
odule build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'prependData'. These properties are valid:
   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }
    at validate (E:\workspace\vue\uview-demo\node_modules\sass-loader\node_modules\schema-utils\dist\validate.js:96:11)
    at Object.loader (E:\workspace\vue\uview-demo\node_modules\sass-loader\dist\index.js:30:28)

**Comment by xtuphe** [comment]
我也遇到了这个问题，求解决

**Comment by smart-shore** [comment]
> 我也遇到了这个问题，求解决

change the version of saas-loader use below

 "sass-loader": "7.3.1"
