### ISSUE TITLE
u-popup组件v-if隐藏建议修改成v-show

### ISSUE THREAD

**Issue by Guxingzhe** [YanxinNet/uView#283]
原因是我页面的checkbox效果无法被缓存。如下图的效果，选中状态，关闭重新打开时，状态没有了。
![image](https://user-images.githubusercontent.com/9564255/88646052-5df41c00-d0f7-11ea-99e8-f3c5f77c166a.png)

![image](https://user-images.githubusercontent.com/9564255/88645721-09e93780-d0f7-11ea-88ff-31a4377ee708.png)
代码片段如下：
`<template>
	<view v-if="visibleSync"`
期望改为：
`<template>
	<view v-show="visibleSync"`

**Comment by tttao7** [comment]
小程序不支持v-show 建议您考虑其他方案

**Comment by Guxingzhe** [comment]
> 小程序不支持v-show 建议您考虑其他方案

感谢你的回答。为了兼容确实只能用v-if

**Comment by tttao7** [comment]
> > 小程序不支持v-show 建议您考虑其他方案
> 
> 感谢你的回答。为了兼容确实只能用v-if

根据最新alpha版本hbx更新日志 应该在最近几个版本 将会适配v-show 届时uView会同步进行优化和更新
