### ISSUE TITLE
关于头像组件官方文档参数错误

### ISSUE THREAD

**Issue by AmosHuKe** [YanxinNet/uView#286]
错误位置：https://www.uviewui.com/components/avatar.html#props

等级图标相关，应该是level，不应该还是sex
show-sex => show-level
sex-bg-color => level-bg-color 

看起来是复制粘贴的哈哈哈😂

![错误位置](https://user-images.githubusercontent.com/32262985/88888457-ec3fdd80-d270-11ea-8fc4-7e2b4e3d8924.png)

**Comment by tttao7** [comment]
已更正 感谢反馈
