### ISSUE TITLE
swiper组件list数组发生变化时的bug

### ISSUE THREAD

**Issue by hope-11** [YanxinNet/uView#30]
当swiper数组list数组发生变化时，如果current值大于了新数组的长度，会出错。请问可否当数组发生变化时重置current=0

**Comment by BeiQiaoT** [comment]
> 当swiper数组list数组发生变化时，如果current值大于了新数组的长度，会出错。请问可否当数组发生变化时重置current=0

您意思是list长度动态变短后，swiper可能存在溢出是吧。好的，我记录一下这个

**Comment by YanxinNet** [comment]
感谢反馈，1.3.1已处理此问题

**Comment by hope-11** [comment]
似乎只重置current=0并不起作用，需要先把swiper销毁再创建才行。。。
