### ISSUE TITLE
CellItem Slot  文档错误

### ISSUE THREAD

**Issue by yanpeng4665** [YanxinNet/uView#31]
### 文档是下面这样
CellItem Slot 
名称 | 说明
title | **自定义左侧标题部分的内容，如需使用，请勿定义title参数，或赋值null即可**
icon | 自定义左侧的图标
right-icon | 自定义右侧图标内容，需设置arrow为false才起作用
label | 自定义label内容，需同时设置use-label-slot为true
### 但是代码是这样的
```
<template>
	<view @tap="click" class="u-cell-item-box" :class="{'u-cell-border': itemIndex > 0 }" hover-stay-time="150" :hover-class="hover ? 'u-hover-class' : ''" :style="{
		backgroundColor: bgColor
	}">
		<view class="u-cell-content">
			<view class="u-icon-wrap" v-if="icon">
				<u-icon size="32" :name="icon" class="u-icon"></u-icon>
			</view>
			<view class="u-icon-wrap">
				<slot name="icon"></slot>
			</view>
			<view class="u-cell-title" :style="[titleStyle]">
				<text class="u-title-text" v-if="title">{{title}}</text>
				<slot name="left"></slot>
			</view>
			<view class="u-cell-value" v-if="value">
				<text class="u-value-text" :style="[valueStyle]" v-if="value">{{value}}</text>
			</view>
			<view v-else class="u-slot-wrap">
				<slot name="right"></slot>
			</view>
			<view :style="[arrowStyle]" class="u-icon-wrap">
				<u-icon v-if="arrow" size="26" class="u-arror-right" color="#969799" name="arrow-right"></u-icon>
			</view>
		</view>
		<view class="u-cell-label" v-if="label" :style="[labelStyle]">
			{{label}}
		</view>
	</view>
</template>
```

**Comment by BeiQiaoT** [comment]
> ### 文档是下面这样
> CellItem Slot
> 名称 | 说明
> title | **自定义左侧标题部分的内容，如需使用，请勿定义title参数，或赋值null即可**
> icon | 自定义左侧的图标
> right-icon | 自定义右侧图标内容，需设置arrow为false才起作用
> label | 自定义label内容，需同时设置use-label-slot为true
> 
> ### 但是代码是这样的
> ```
> <template>
> 	<view @tap="click" class="u-cell-item-box" :class="{'u-cell-border': itemIndex > 0 }" hover-stay-time="150" :hover-class="hover ? 'u-hover-class' : ''" :style="{
> 		backgroundColor: bgColor
> 	}">
> 		<view class="u-cell-content">
> 			<view class="u-icon-wrap" v-if="icon">
> 				<u-icon size="32" :name="icon" class="u-icon"></u-icon>
> 			</view>
> 			<view class="u-icon-wrap">
> 				<slot name="icon"></slot>
> 			</view>
> 			<view class="u-cell-title" :style="[titleStyle]">
> 				<text class="u-title-text" v-if="title">{{title}}</text>
> 				<slot name="left"></slot>
> 			</view>
> 			<view class="u-cell-value" v-if="value">
> 				<text class="u-value-text" :style="[valueStyle]" v-if="value">{{value}}</text>
> 			</view>
> 			<view v-else class="u-slot-wrap">
> 				<slot name="right"></slot>
> 			</view>
> 			<view :style="[arrowStyle]" class="u-icon-wrap">
> 				<u-icon v-if="arrow" size="26" class="u-arror-right" color="#969799" name="arrow-right"></u-icon>
> 			</view>
> 		</view>
> 		<view class="u-cell-label" v-if="label" :style="[labelStyle]">
> 			{{label}}
> 		</view>
> 	</view>
> </template>
> ```

**Comment by BeiQiaoT** [comment]
> ### 文档是下面这样
> CellItem Slot
> 名称 | 说明
> title | **自定义左侧标题部分的内容，如需使用，请勿定义title参数，或赋值null即可**
> icon | 自定义左侧的图标
> right-icon | 自定义右侧图标内容，需设置arrow为false才起作用
> label | 自定义label内容，需同时设置use-label-slot为true
> 
> ### 但是代码是这样的
> ```
> <template>
> 	<view @tap="click" class="u-cell-item-box" :class="{'u-cell-border': itemIndex > 0 }" hover-stay-time="150" :hover-class="hover ? 'u-hover-class' : ''" :style="{
> 		backgroundColor: bgColor
> 	}">
> 		<view class="u-cell-content">
> 			<view class="u-icon-wrap" v-if="icon">
> 				<u-icon size="32" :name="icon" class="u-icon"></u-icon>
> 			</view>
> 			<view class="u-icon-wrap">
> 				<slot name="icon"></slot>
> 			</view>
> 			<view class="u-cell-title" :style="[titleStyle]">
> 				<text class="u-title-text" v-if="title">{{title}}</text>
> 				<slot name="left"></slot>
> 			</view>
> 			<view class="u-cell-value" v-if="value">
> 				<text class="u-value-text" :style="[valueStyle]" v-if="value">{{value}}</text>
> 			</view>
> 			<view v-else class="u-slot-wrap">
> 				<slot name="right"></slot>
> 			</view>
> 			<view :style="[arrowStyle]" class="u-icon-wrap">
> 				<u-icon v-if="arrow" size="26" class="u-arror-right" color="#969799" name="arrow-right"></u-icon>
> 			</view>
> 		</view>
> 		<view class="u-cell-label" v-if="label" :style="[labelStyle]">
> 			{{label}}
> 		</view>
> 	</view>
> </template>
> ```

右侧图标arrow点击效果为true也是可以的呀，这个我记录下来，之后确认
