### ISSUE TITLE
Grid组件在微信小程序中无法正确计算出grid-item的宽度

### ISSUE THREAD

**Issue by AlwaysLoveme** [YanxinNet/uView#32]
如题，看了源代码，里面计算宽度有用到$uGetRect方法，但是我全局搜索了，原型上并没有挂载这个方法？求修复！！！

**Comment by BeiQiaoT** [comment]
> 如题，看了源代码，里面计算宽度有用到$uGetRect方法，但是我全局搜索了，原型上并没有挂载这个方法？求修复！！！

感谢提出的issues，我们之后会确认

**Comment by AlwaysLoveme** [comment]
> > 如题，看了源代码，里面计算宽度有用到$uGetRect方法，但是我全局搜索了，原型上并没有挂载这个方法？求修复！！！
> 
> 感谢提出的issues，我们之后会确认

我之后仔细看了一下，是在mixins里面，但是$uGetRect里面区分支付宝和其他小程序的时候逻辑貌似反了。，
