### ISSUE TITLE
u-tabbar Cannot read property 'count' of undefined"问题

### ISSUE THREAD

**Issue by XiaoWei3209** [YanxinNet/uView#334]
24行代码
```
<u-badge v-if="item.count > 0" :count="item.count" :is-dot="item.isDot" :offset="[-2, getOffsetRight(item.count, item.isDot)]"
></u-badge>
```
`v-if="item.count > 0"`中，如果item.count == null || item.count == undefined 就会出错；
我修改了这样
`v-if="item && item.count && item.count > 0"`

**Comment by jackytse** [comment]
我也遇到这个问题了
升级到hbuilderX 2.8.5.20200812 版本后，在微信小程序中运行会报这个错

**Comment by XiaoWei3209** [comment]
> 我也遇到这个问题了
> 升级到hbuilderX 2.8.5.20200812 版本后，在微信小程序中运行会报这个错
> 在hbuilderX 2.8.3.20200728 版本不会报这个错

希望可以早日完善，就是怕框架更新导致报错；

**Comment by tttao7** [comment]
此问题已修复 是因为hbx导致 感谢您的反馈
