### ISSUE TITLE
u-tabs在ios微信小程序里性能低下

### ISSUE THREAD

**Issue by liuhongy1985** [YanxinNet/uView#397]
u-tabs在ios微信小程序里性能低下，切换需要2-4秒

**Comment by tttao7** [comment]
@liuhongy1985 请贴一下相关代码 我们排查下原因 不知道您在示例项目是否也是这么卡顿

**Comment by liuhongy1985** [comment]
官方的微信小程序u-tabs点击后没有问题，但是使用uni导入https://ext.dcloud.net.cn/plugin?id=1593项目使用u-tabs点击后2秒左右才会切换和我自己引入项目是一样的

**Comment by liuhongy1985** [comment]
<template>
  <view class="main">
    <u-tabs
      duration="0"
      :list="tabList"
      :is-scroll="false"
      :current="current"
      @change="change"></u-tabs>
    <view>
      <view class="list">
        <view class="list-item">
          <view class="item-info">
            <view class="list-img item">
              <u-image
                width="80px"
                height="60px"
                :src="src"></u-image>
            </view>
            <view class="item item-flex">
              <p>单位</p>
              <p>部门</p>
            </view>
          </view>
          <view>
            <u-cell-item
              :title-style="{'font-size': '14px'}"
              title="未处理"
              :arrow="true"
              :border-bottom="false"></u-cell-item>
            <p>2020-8-29</p>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script>
import API from '@/api/home.js'

export default {
  data () {
    return {
      tabList: [
        {
          name: '未处理',
          value: 0,
        }, {
          name: '已接受',
          value: 1,
        }, {
          name: '已完成',
          value: 2,
        },
      ],
      current: 0,
      listParams: {
        page: {
          pageIndex: 1,
          pageSize: 20,
        },
      },
      dataList: [
        { title: 'cs', createTimeF: '2-9' },
        { title: 'cs', createTimeF: '2-9' },
        { title: 'cs', createTimeF: '2-9' },
        { title: 'cs', createTimeF: '2-9' },
      ],
      totalPage: '',
    }
  },
  onLoad () {
    //this.getList()
  },
  methods: {
    change (index) {
      this.current = index
    },
    getList () {
      API.assetsInfoList(this.listParams).then(res => {
        this.dataList = res.data
        this.totalPage = res.pageVo.totalNum
      }).catch(error => {
        console.log(error)
        //this.$message.error(error.message)
      })
    },
  },
}
</script>

<style
  lang="scss"
  scoped>
.list {
  padding: 10px;
}
.list-item {
  display: -webkit-flex;
  display: flex;
  justify-content: space-between;
}
.item-info {
  display: -webkit-flex;
  display: flex;
  .item {
    padding: 5px;
  }
}
.item-flex {
  display: -webkit-flex;
  display: flex;
  flex-direction: column;
}
</style>

**Comment by liuhongy1985** [comment]
<u-tabs
      duration="0"
      :list="tabList"
      :is-scroll="false"
      :current="current"
      @change="change"></u-tabs>

**Comment by tttao7** [comment]
会不会是你的环境问题，因为示例项目，我这边跑起来也是正常的。

**Comment by liuhongy1985** [comment]
确实是不同的环境，官方的小程序示例没问题，我发布到正式也没问题，唯独通过uniapp运行到小程序开发工具会出现这种清空

**Comment by tttao7** [comment]
@liuhongy1985 应该是开发环境下 你的js过大导致和页面等原因导致的 这是我的一点推测 如果受到影响建议重装下环境试试 那我这边就帮你把issue关闭了 感谢您对uView的支持
