### ISSUE TITLE
请问是否考虑支持下拉框？

### ISSUE THREAD

**Issue by thqy39** [YanxinNet/uView#4]
感谢作者开源这么美观、精致、强大的UI库，顺利来求个下拉框方案。谢谢

**Comment by bmmanmyt** [comment]
下拉框方案正在收集整理，当然，如果您有相关的案例，可以提供给我们，感谢对uview的支持。

**Comment by bmmanmyt** [comment]
> 感谢作者开源这么美观、精致、强大的UI库，顺利来求个下拉框方案。谢谢

下拉框方案正在收集整理，当然，如果您有相关的案例，可以提供给我们，感谢对uview的支持。
