### ISSUE TITLE
建议：SwipeAction 滑动单元格 优化

### ISSUE THREAD

**Issue by CjoyHome** [YanxinNet/uView#42]
在测试官方demo时候发现以下问题
1、在进行SwipeAction 滑动时，滑动一点会自动弹出，但是未弹出整个操作栏，隐藏了一些
2、在进行点击操作时，点击状态为 '打开' 时，操作栏未完全滑出，隐藏了部分操作栏（与第一栏问题一样）

**Comment by BeiQiaoT** [comment]
我这边没有复现出您所说的的情况，可以加qq群1042987248探讨一下

**Comment by BeiQiaoT** [comment]
> 在测试官方demo时候发现以下问题
> 1、在进行SwipeAction 滑动时，滑动一点会自动弹出，但是未弹出整个操作栏，隐藏了一些
> 2、在进行点击操作时，点击状态为 '打开' 时，操作栏未完全滑出，隐藏了部分操作栏（与第一栏问题一样）

我这边没有复现出您所说的的情况，可以加qq群1042987248探讨一下
