### ISSUE TITLE
升级到1.6.6后form组件很多属性失效了

### ISSUE THREAD

**Issue by jacky8466** [YanxinNet/uView#425]
比如：
 label-align="right" label-position="left"label-width="150"
<u-form :model="form" ref="uForm"  label-align="right" label-position="top
![11111](https://user-images.githubusercontent.com/11418894/92192024-b1e0e600-ee97-11ea-9cb6-075419f51ba2.png)
" :error-type="errorType">
无效

**Comment by i-arjan** [comment]
升级后也出现同样的问题,回滚到上一个版本正常

**Comment by tttao7** [comment]
试试1.6.7

**Comment by jacky8466** [comment]
> 试试1.6.7
新版已解决
