### ISSUE TITLE
升级到1.28，Mask层show:false无效

### ISSUE THREAD

**Issue by missy0u** [YanxinNet/uView#44]
![image](https://user-images.githubusercontent.com/3926664/82692084-9f002800-9c91-11ea-909f-2a002f7f5509.png)

Mask层 show:false，还是被Mask层阻档不能操作，去掉z-index或position正常，1.27没有这问题

**Comment by BeiQiaoT** [comment]
> ![image](https://user-images.githubusercontent.com/3926664/82692084-9f002800-9c91-11ea-909f-2a002f7f5509.png)
> 
> Mask层 show:false，还是被Mask层阻档不能操作，去掉z-index或position正常，1.27没有这问题

收到
