### ISSUE TITLE
Grid组件出问题

### ISSUE THREAD

**Issue by CYYSILVER** [YanxinNet/uView#45]
前面用的好好的，今天npm update一下，就出问题了。
![gird-item没有宽度](https://user-images.githubusercontent.com/48582184/82705304-0629d680-9caa-11ea-9d9d-27b27ed59462.png)
gird组件里所有东西都挤到了一起
![gird-item没有宽度](https://user-images.githubusercontent.com/48582184/82705311-07f39a00-9caa-11ea-8f6b-18878cab7054.png)
gird-item组件没有宽度，查看源码，发现
/lib/mixin/mixin.js中
![Snipaste_2020-05-23_04-02-20](https://user-images.githubusercontent.com/48582184/82705466-46895480-9caa-11ea-88cf-93d1cf07f203.png)
这。。。
写反了吧？？？
把它改回来就恢复正常了
![Snipaste_2020-05-23_04-03-49](https://user-images.githubusercontent.com/48582184/82705565-6d478b00-9caa-11ea-8c3e-70131b379de0.png)
![Snipaste_2020-05-23_04-05-17](https://user-images.githubusercontent.com/48582184/82705655-a2ec7400-9caa-11ea-812f-c7b5c00526c8.png)

**Comment by BeiQiaoT** [comment]
> 前面用的好好的，今天npm update一下，就出问题了。
> ![gird-item没有宽度](https://user-images.githubusercontent.com/48582184/82705304-0629d680-9caa-11ea-9d9d-27b27ed59462.png)
> gird组件里所有东西都挤到了一起
> ![gird-item没有宽度](https://user-images.githubusercontent.com/48582184/82705311-07f39a00-9caa-11ea-8f6b-18878cab7054.png)
> gird-item组件没有宽度，查看源码，发现
> /lib/mixin/mixin.js中
> ![Snipaste_2020-05-23_04-02-20](https://user-images.githubusercontent.com/48582184/82705466-46895480-9caa-11ea-88cf-93d1cf07f203.png)
> 这。。。
> 写反了吧？？？
> 把它改回来就恢复正常了
> ![Snipaste_2020-05-23_04-03-49](https://user-images.githubusercontent.com/48582184/82705565-6d478b00-9caa-11ea-8c3e-70131b379de0.png)
> ![Snipaste_2020-05-23_04-05-17](https://user-images.githubusercontent.com/48582184/82705655-a2ec7400-9caa-11ea-812f-c7b5c00526c8.png)

mixin条件编译问题，已在处理

**Comment by tttao7** [comment]
此问题已修复 感谢反馈
