### ISSUE TITLE
打包官方demoh5页面显示异常

### ISSUE THREAD

**Issue by clz1072627512** [YanxinNet/uView#452]
![image](https://user-images.githubusercontent.com/22511736/92985179-e3cef980-f4e2-11ea-8796-6a4faf5fc8a7.png)

**Comment by tttao7** [comment]
@clz1072627512 这个有可能是你的样式问题，建议检查下你的uView安装配置。

**Comment by clz1072627512** [comment]
我想问下你们打包h5演示是用hbuilderx是多少版本的

**Comment by clz1072627512** [comment]
> @ clz1072627512这个有可能是你的样式问题，建议检查下你的uView安装配置。

你们打包h5的演示项目时用Hbuilderx多少版本的

**Comment by clz1072627512** [comment]
> @tttao7 你们打包h5的演示项目时用Hbuilderx多少版本的

**Comment by tttao7** [comment]
@clz1072627512 一般是最新的前一个版本或者最新的版本

**Comment by clz1072627512** [comment]
@tttao7  我打包的看是uni默认的样式没有应用上
![image](https://user-images.githubusercontent.com/22511736/92987520-b3dd2180-f4f5-11ea-8919-603008873aaf.png)
