### ISSUE TITLE
Picker组件地区模式是否可以用6位的区域编码？

### ISSUE THREAD

**Issue by weixisheng** [YanxinNet/uView#46]
首先赞一下开源项目、的确很优秀。这里有个小建议：
Picker选择器的地区模式，使用的数据源的区域编码长度不一，是否考虑使用统一长度的编码格式
["13", "1303", "130304"]  => ["130000", "130300", "130304"]，后者的格式项目中好像看到的多一点。

**Comment by BeiQiaoT** [comment]
> 首先赞一下开源项目、的确很优秀。这里有个小建议：
> Picker选择器的地区模式，使用的数据源的区域编码长度不一，是否考虑使用统一长度的编码格式
> ["13", "1303", "130304"] => ["130000", "130300", "130304"]，后者的格式项目中好像看到的多一点。

我们地址库就是那样的编码，建议picker的多列模式传入自定义数据

**Comment by weixisheng** [comment]
谢谢，也可以。
简单的做法就是写个padEnd方法填0用于提交到数据库，然后trimEnd去0保持跟组件编码同步
