### ISSUE TITLE
u-tabs 组件1.2.8版本底部的短线失灵

### ISSUE THREAD

**Issue by AlwaysLoveme** [YanxinNet/uView#47]
今天刚npm update了一下，发现u-tabs底下的横线不随着滚动了，位置也不对，望尽快修复一下

**Comment by qinkaiyuan** [comment]
微信开发者工具遇到类似问题，原因为 mixin不支持条件编译导致

**Comment by BeiQiaoT** [comment]
> 今天刚npm update了一下，发现u-tabs底下的横线不随着滚动了，位置也不对，望尽快修复一下

mixin已在处理

**Comment by qinkaiyuan** [comment]
vue-cli方式创建的项目，uniapp未编译node_modules里面 js里的 条件编译导致的。

uview的mixin文件里面有条件编译代码，uniapp未进行编译

**Comment by tttao7** [comment]
> vue-cli方式创建的项目，uniapp未编译node_modules里面 js里的 条件编译导致的。
> 
> uview的mixin文件里面有条件编译代码，uniapp未进行编译

和uniapp确认过 所以建议使用下载方式

**Comment by pitilesszgw** [comment]
> 今天刚npm update了一下，发现u-tabs底下的横线不随着滚动了，位置也不对，望尽快修复一下

您好问下这个问题现在已经修复了么
