### ISSUE TITLE
checkbox 勾选显示问题

### ISSUE THREAD

**Issue by EDGDK** [YanxinNet/uView#470]
使用checkboxGroup，给checkbox 设置了v-model布尔值默认为false，勾选后未选中，页面中还有u-action-sheet组件，打开下拉框后勾选状态才出现，是渲染问题吗？
代码：
<u-checkbox-group @change="checkboxGroupChange">
			<u-checkbox 
				v-model="item.checked" 
				v-for="(item, index) in list" :key="index" 
				:name="item.name"
			>{{item.name}}</u-checkbox>
		</u-checkbox-group>
不过我的list是通过接口渲染的

**Comment by EDGDK** [comment]
补充：像是没有主动渲染 我点击表单其他地方他就显示勾选状态了

**Comment by EDGDK** [comment]
果然是渲染问题 我加上this.$nextTick()就行了

**Comment by zhangpfan** [comment]
遇到同样的问题，楼主这个this.$nextTick()怎么处理？
