### ISSUE TITLE
每次更新，我都要改一堆你们带来的UI问题，搞什么啊

### ISSUE THREAD

**Issue by chenjiecloud** [YanxinNet/uView#473]

**Comment by chenjiecloud** [comment]
loadmore 为什么要改，
<img width="355" alt="WX20200918-094033@2x" src="https://user-images.githubusercontent.com/31178795/93545528-38ff8500-f993-11ea-86fa-22e4dfdd801c.png">
这不丑吗？

**Comment by chenjiecloud** [comment]
loading 中还加这个？想什么呢？

**Comment by jarrelljiang** [comment]
怒顶赞，项目中一堆的UI覆盖代码，越来越难维护了，真想自己写组件了

**Comment by tttao7** [comment]
收到反馈 不好意思了 也请体谅下
