### ISSUE TITLE
建议: 添加tabbar组件

### ISSUE THREAD

**Issue by 2460392754** [YanxinNet/uView#48]

**Comment by BeiQiaoT** [comment]
> _No description provided._

tabbar我们有制作的想法，但建议以原生tabbar为主，以避免出现更多的问题

**Comment by 2460392754** [comment]
原生的tabbar限制太多了，不利于功能的扩展

**Comment by BeiQiaoT** [comment]
> 原生的tabbar限制太多了，不利于功能的扩展

原生在app端已经有很多支持了，但是小程序和h5还没有

**Comment by 2460392754** [comment]
小程序原生的`tabbar`根本就没法扩展，只能自己模拟一个

**Comment by ldsenow** [comment]
强烈建议添加tabbar组件
