### ISSUE TITLE
HBuilder X2.7.5无代码提示？

### ISSUE THREAD

**Issue by AR1N** [YanxinNet/uView#50]
HBuilder X2.7.5无代码提示，是怎么回事啊

**Comment by BeiQiaoT** [comment]
> HBuilder X2.7.5无代码提示，是怎么回事啊

组件正常使用，无代码提示，一般是HBuilderX的问题，建议重启，或者重构项目索引，或者npm方式引入的，在根目录下放uview源码

**Comment by lanrain** [comment]
npm引入的为什么要在根目录下放uview源码呢？

**Comment by wangyuan0217** [comment]
我按照说的吧  uview-ui目录复制到根目录下就好了。。。但是看着别扭。。。
