### ISSUE TITLE
indexlist 索引列表文档错误。

### ISSUE THREAD

**Issue by xiaowang04821** [YanxinNet/uView#51]
![K(~WK7_VE25XU%%E7{B4FNB](https://user-images.githubusercontent.com/63433913/82852702-32f21e00-9f36-11ea-8994-f689cb2d460c.png)
文档中的``highlight-color``在实际运用过程中不起作用。查看了源码，源码中的props为``activeColor``,请修复文档或者更改源码。

**Comment by BeiQiaoT** [comment]
> ![K(~WK7_VE25XU%%E7{B4FNB](https://user-images.githubusercontent.com/63433913/82852702-32f21e00-9f36-11ea-8994-f689cb2d460c.png)
> 文档中的`highlight-color`在实际运用过程中不起作用。查看了源码，源码中的props为`activeColor`,请修复文档或者更改源码。

收到
