### ISSUE TITLE
upload组件进入success回调后data转JSON格式

### ISSUE THREAD

**Issue by 2460392754** [YanxinNet/uView#54]
可以根据`uni.uploadFile`在`success`回调函数的http响应头里的`content-type`参数，来进行选择性的data对象转JSON。

**Comment by BeiQiaoT** [comment]
> 可以根据`uni.uploadFile`在`success`回调函数的http响应头里的`content-type`参数，来进行选择性的data对象转JSON。

我来记录一下您这个建议

**Comment by YanxinNet** [comment]
问题已改正，感谢反馈
