### ISSUE TITLE
u-grid-item custom-style 绑定的的对象属性不生效

### ISSUE THREAD

**Issue by yanchao0204** [YanxinNet/uView#580]
### Bug描述: 
uView 文档中u-grid-item custom-style 绑定的的对象属性不生效
![image](https://user-images.githubusercontent.com/18110912/97666307-4e022480-1ab8-11eb-979b-12e426b526ca.png)
### 分析原因:
**uni-app 文档说不支持customStyle绑定的样式**
[https://uniapp.dcloud.io/use?id=class-与-style-绑定](url)

![image](https://user-images.githubusercontent.com/18110912/97666557-e8fafe80-1ab8-11eb-968d-b4bdb329b4ba.png)
###解决方案:
修改源码u-grid-item.vue 文件
```
// 将:style="customStyle"  改为  :style="[customStyle]", 解决
<view class="u-grid-item-box" :style="[customStyle]" >...
```
![image](https://user-images.githubusercontent.com/18110912/97666393-87d32b00-1ab8-11eb-8945-a9dc7c0d80b5.png)

**Comment by YanxinNet** [comment]
已改正，感谢反馈
