### ISSUE TITLE
1.7.3 u-table u-td width 在H5中正常，微信小程序中不生效。

### ISSUE THREAD

**Issue by whoooami** [YanxinNet/uView#586]

**Comment by LiuTianjie** [comment]
这好像是没有设置它本身的宽度，
u-th和u-td组件中添加
style.width=\`\${parseInt(this.width)}vw\`;
实测有效

**Comment by LiuTianjie** [comment]
> _No description provided._

这好像是没有设置它本身的宽度，
u-th和u-td组件中添加
style.width=\`${parseInt(this.width)}vw\`;
实测有效

**Comment by whoooami** [comment]
嗯嗯，是可以的。多谢兄台 @LiuTianjie

**Comment by iosluoyang** [comment]
请问是如何增加style.width=`${parseInt(this.width)}vw`; 这行代码的？
我看了一下小程序是因为main.css中设置了u-td 和u-th的lflex为1的原因导致td和th平分当前tr，所以尝试着使用scss重写u-td和u-th的flex,但需要每个都有width 。 不知您说的style.width=`${parseInt(this.width)}vw`; 是怎样加到u-th或者u-td中的呢？ 如果是直接作为属性添加没有width这个属性哈哈。

**Comment by whoooami** [comment]
th/td都修改
-				if (this.width != "auto") style.flex = `0 0 ${this.width}`;
+				if (this.width != "auto") {
+					style.flex = `0 0 ${this.width}`;
+					style.width=`${parseInt(this.width)}vw`;
+				};

**Comment by iosluoyang** [comment]
我尝试着按照你的分享改了uview中的u-th和u-td
分别为:
u-th: 
![u-th](https://user-images.githubusercontent.com/12808629/119090947-dfc68480-ba3e-11eb-9bbe-d7b9a01e9eea.png)

u-td:
![u-td](https://user-images.githubusercontent.com/12808629/119091030-02589d80-ba3f-11eb-8f31-0c96c7adce92.png)


针对于u-td和u-th的scss中的flex没有做更改  这样子在微信小程序上测试发现还是会平分当前的tr，审查元素发现是因为该style仅作用于子级组件  没有作用于父级组件导致依旧是计算不准确，请问能详细地分享一下如何进行更改吗？
![wechat_u-th](https://user-images.githubusercontent.com/12808629/119097954-e7d6f200-ba47-11eb-8b4c-0ce2fab70a1a.png)



多谢！

**Comment by whoooami** [comment]
看起来您用的应该是新版的uiview。新版的不用修改。您尝试下用百分比的方式试下
<u-td class="u-td" width="29%">测试</u-td>
![image](https://user-images.githubusercontent.com/2926551/119258745-9f613500-bbfd-11eb-9609-511cad589d53.png)

**Comment by iosluoyang** [comment]
@whoooami 嗨，兄弟。我目前用的却是是较新版本的uview 1.8.3版本
按照你的方法在u-th 和 u-td中添加style.width= `${parseInt(this.width)}vw` 确实会在小程序中按照设置的width进行布局，但是这么做有一些限制点
第一就是因为后面增加了vw，所以宽度只能设置百分比而不能设置具体的数值(建议可以做个判断有百分比的时候用百分比，没有百分比的时候就不加vw了，使用真实宽度数值)

第二个就是每一个td都是基于整个窗口的vw来设置宽度，而不是当前table的父组件宽度，所以会出现如果整个table的宽度并不是100vw的情况下，其中的单元格宽度是不准确的。

另外因为我用了合并单元格(即在某一个u-td中渲染多个u-tr)，所以如果按照您的百分比方式在合并的子单元格中每一个单元格也都是用的vw，无法根据它所在的当前单元格为基准进行布局

综上，由于我有合并单元格的需求，所以最后使用了官方的uni-table，将每一个列的单元格用固定的数值width来进行设定实现

最后，感谢您的耐心解答和回复，如果后续有更好的方案，请一定多多指导。我的Q： 3029068348
