### ISSUE TITLE
启动的时候报错，什么原因呢？

### ISSUE THREAD

**Issue by xgj1988** [YanxinNet/uView#587]
![image](https://user-images.githubusercontent.com/8272614/97828368-e212fc80-1d01-11eb-9820-e254ec5bfd4c.png)

**Comment by xgj1988** [comment]
11:47:57.009 Module build failed (from ./node_modules/postcss-loader/src/index.js):
11:47:57.013 SyntaxError
11:47:57.016 (113:12) Unknown word
11:47:57.017   111 | // 定义flex等分
11:47:57.021   112 | @for $i from 0 through 12 {
11:47:57.025 > 113 | 	.u-flex-#{$i} {
11:47:57.030       | 	          ^
11:47:57.035   114 | 		flex: $i;
11:47:57.039   115 | 	}

**Comment by tttao7** [comment]
安装问题 检查下APP.vue和uni.scss

**Comment by Kchengz** [comment]
App.vue 里面的style标签记得加上 lang="scss" 就好了
