### ISSUE TITLE
uni-app + uviewui 启动报错 Module parse failed: Unexpected token (8:8)

### ISSUE THREAD

**Issue by Exclusive-gfj** [YanxinNet/uView#628]
ERROR  Failed to compile with 1 errors                                                                                                                                                     5:48:38 PM

 error  in ./node_modules/uview-ui/libs/function/route.js

Module parse failed: Unexpected token (8:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| class Router {
|       // 原始属性定义
>       config = {
|               type: 'navigateTo',
|               url: '',

 @ ./node_modules/uview-ui/index.js 29:0-44 80:8-13
 @ ./src/main.js

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

node版本： v14.5.0
npm版本：6.14.5
uView版本：1.8.1

**Comment by Exclusive-gfj** [comment]
node版本： v14.5.0
npm版本：6.14.5

**Comment by windylaugit** [comment]
+1

**Comment by jacknewbee** [comment]
+1

**Comment by renxiaomeng** [comment]
+1

**Comment by LgxWalker** [comment]
也遇到同样的，回退版本到1.7.8才可以

**Comment by kyxiao** [comment]
+1

**Comment by xmy1024** [comment]
+1

**Comment by yanthink** [comment]
1、安装 babel 插件
    
    npm i @babel/preset-env @babel/plugin-transform-runtime @babel/plugin-proposal-class-properties –D

2、通过 babel.config.js 进行配置 babel

```js
const plugins = [
  '@babel/plugin-transform-runtime', ['@babel/plugin-proposal-class-properties', { loose: true }],
];

if (process.env.UNI_OPT_TREESHAKINGNG) {
  plugins.push(require('@dcloudio/vue-cli-plugin-uni-optimize/packages/babel-plugin-uni-api/index.js'));
}

if (
  (
    process.env.UNI_PLATFORM === 'app-plus' &&
    process.env.UNI_USING_V8
  ) ||
  (
    process.env.UNI_PLATFORM === 'h5' &&
    process.env.UNI_H5_BROWSER === 'builtin'
  )
) {
  const path = require('path');

  const isWin = /^win/.test(process.platform);

  const normalizePath = path => (isWin ? path.replace(/\\/g, '/') : path);

  const input = normalizePath(process.env.UNI_INPUT_DIR);
  try {
    plugins.push([
      require('@dcloudio/vue-cli-plugin-hbuilderx/packages/babel-plugin-console'),
      {
        file(file) {
          file = normalizePath(file);
          if (file.indexOf(input) === 0) {
            return path.relative(input, file);
          }
          return false;
        },
      },
    ]);
  } catch (e) {
  }
}

process.UNI_LIBRARIES = process.UNI_LIBRARIES || ['@dcloudio/uni-ui'];
process.UNI_LIBRARIES.forEach(libraryName => {
  plugins.push([
    'import',
    {
      'libraryName': libraryName,
      'customName': (name) => {
        return `${libraryName}/lib/${name}/${name}`;
      },
    },
  ]);
});

module.exports = {
  presets: [
    '@babel/preset-env',
    [
      '@vue/app',
      {
        modules: 'commonjs',
        useBuiltIns: process.env.UNI_PLATFORM === 'h5' ? 'usage' : 'entry',
      },
    ],
  ],
  plugins,
};
```

3、通过 vue.config.js 配置 webpack loader

```js
// https://uniapp.dcloud.io/collocation/vue-config

const path = require('path');

module.exports = {
  chainWebpack: (config) => {
    config.module.rule('js')
      .exclude.clear().end()
      .include.clear().add(path.resolve(__dirname,'src')).add(path.resolve(__dirname,'node_modules/uview-ui'));
  },
};
```

**Comment by Exclusive-gfj** [comment]
> 1，安装babel插件
> 
> ```
> npm i @babel/preset-env @babel/plugin-transform-runtime @babel/plugin-proposal-class-properties –D
> ```
> 
> 2，通过babel.config.js进行配置babel
> 
> ```js
> const  plugins  =  [ 
>   '@ babel / plugin-transform-runtime' ， [ '@ babel / plugin-proposal-class-properties' ， { 松散：真 } ] ，
> ] ;
> 
> 如果 （过程。ENV 。UNI_OPT_TREESHAKINGNG ） {
>   插件。推送（要求（'@ dcloudio / vue-cli-plugin-uni-optimize / packages / babel-plugin-uni-api / index.js' ））; 
> }
> 
> 如果 （
>   （
>     过程。ENV 。UNI_PLATFORM  ===  '应用加'  &&
>     过程。ENV 。UNI_USING_V8 
>   ） || 
>   （
>     过程。ENV 。UNI_PLATFORM  ===  'H5'  &&
>     过程。ENV 。UNI_H5_BROWSER  ===  '内置' 
>   ）
> ） { 
>   const  path  =  require （'path' ）;
> 
>   const  isWin  =  / ^ win / 。试验（处理。平台）;
> 
>   常量 normalizePath  = 路径 =>  （isWin？路径。代替（/ \\ /克， '/' ）：路径）;
> 
>   常量 输入 =  normalizePath （过程。ENV 。UNI_INPUT_DIR ）; 
>   试试 {
>     插件。推（[
>       要求（'@ dcloudio / VUE-CLI-插件-hbuilderx /包/巴别-插件控制台' ），
>       {
>         文件（文件） {
>           文件 =  normalizePath （文件）;
>           如果 （文件。的indexOf （输入） == =  0 ） {
>             返回 路径。相对（输入， 文件）; 
>           }
>           返回 假的; 
>         } ，
>       } ，
>     ] ））；
>   } 抓住 （e ） { 
>   } 
> }
> 
> 过程。UNI_LIBRARIES  = 流程。UNI_LIBRARIES  ||  [ '@ dcloudio / uni-ui' ] ; 
> 过程。UNI_LIBRARIES 。的forEach （库名称 =>  {
>   插件。推送（[ 
>     '进口' ，
>     { 
>       '库名称'：库名称，
>       'customName' ：（名称） =>  {
>         返回 ` $ {库名称} / LIB / $ {名称}/${name}`;
>       },
>     },
>   ]);
> });
> 
> 模块。出口 =  {
>   预设：[ 
>     '@ babel / preset-env' ，
>     [ 
>       '@ vue / app' ，
>       {
>         模块：'commonjs' ，
>         useBuiltIns：process 。ENV 。UNI_PLATFORM  ===  'h5'吗？'usage'：'entry' ，
>       } ，
>     ] ，
>   ] ，
>   插件，
> } ;
> ```
> 
> 3，通过vue.config.js配置webpack加载器
> 
> ```js
> // https://uniapp.dcloud.io/collocation/vue-config
> 
> const path = require('path');
> 
> module.exports = {
>   chainWebpack: (config) => {
>     config.module.rule('js')
>       .exclude.clear().end()
>       .include.clear().add(path.resolve(__dirname,'src')).add(path.resolve(__dirname,'node_modules/uview-ui'));
>   },
> };
> ```
