### ISSUE TITLE
HBuilder X创建的uni-app，已经安装scss插件,报错看不懂！

### ISSUE THREAD

**Issue by ChengHuiHe** [YanxinNet/uView#63]
1、我下载1.2.9.zip, 解压获取 uview-ui 放到我的工程根目录
2、App.vue
配置
<style lang="scss">
	/* uni.scss */
	@import "@/uview-ui/index.scss";
	@import "@/uview-ui/theme.scss";
</style>
3、main.js
配置
import Vue from 'vue'
import App from './App'
// 使用 uview-ui
import uView from 'uview-ui';
Vue.use(uView);
4、pages.json
配置
{
	"easycom": {
			"^u-(.*)": "@/uview-ui/components/u-$1/u-$1.vue"
		},
	"pages":[{}]
}
最后，还是出现了下面的问题，不知道大家在使用的时候有没有类似的问题：

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
23:31:50.487 SassError: Undefined variable: "$u-type-primary-light".
23:31:50.494         on line 2 of ../../../../../../Users/chenghuihe/Desktop/HbuilderPet/uview-ui/libs/css/color.scss
23:31:50.495 >> 	color: $u-type-primary-light!important;
23:31:50.501    --------^

**Comment by BeiQiaoT** [comment]
> 1、我下载1.2.9.zip, 解压获取 uview-ui 放到我的工程根目录
> 2、App.vue
> 配置
> 
> <style lang="scss"> /* uni.scss */ @import "@/uview-ui/index.scss"; @import "@/uview-ui/theme.scss"; </style>
> 3、main.js
> 配置
> import Vue from 'vue'
> import App from './App'
> // 使用 uview-ui
> import uView from 'uview-ui';
> Vue.use(uView);
> 4、pages.json
> 配置
> {
> "easycom": {
> "^u-(.*)": "@/uview-ui/components/u-$1/u-$1.vue"
> },
> "pages":[{}]
> }
> 最后，还是出现了下面的问题，不知道大家在使用的时候有没有类似的问题：
> 
> Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> 23:31:50.487 SassError: Undefined variable: "$u-type-primary-light".
> 23:31:50.494 on line 2 of ../../../../../../Users/chenghuihe/Desktop/HbuilderPet/uview-ui/libs/css/color.scss
> 23:31:50.495 >> color: $u-type-primary-light!important;
> 23:31:50.501 --------^

下载安装方式图文教程链接：
 https://blog.csdn.net/qq_33162604/article/details/105996312 
------------------------------
npm安装方式图文教程链接：
 https://blog.csdn.net/u013350495/article/details/106042826 
------------------------------
请仔细阅读官方文档及教程文档。如果还不行，检查HBuilderX，或者检查是否有第三方组件和uView的组件冲突。

**Comment by xiejibiao** [comment]
请问您解决了吗？我也遇到这个问题了

**Comment by YouYII** [comment]
```HTML

<style lang="scss">
@import "uview-ui/theme.scss";#加上这一行
@import "uview-ui/index.scss";

</style>

```

**Comment by EdmodoYunjiang** [comment]
根目录下新建一个`uni.scss`, 添加下面代码
```
/* uni.scss */
@import 'uview-ui/theme.scss';
```
