### ISSUE TITLE
uni-cli 中 uview1.8.1，Vue.use(uview) 报错

### ISSUE THREAD

**Issue by TuiMao233** [YanxinNet/uView#634]
![image](https://user-images.githubusercontent.com/49724027/99476453-8c8a5100-298b-11eb-9819-6ffe2718fcb4.png)

**Comment by bulolo** [comment]
![image](https://user-images.githubusercontent.com/10026498/99510131-a181d700-29c1-11eb-9df4-c5b1d152013e.png)

**Comment by 935462216** [comment]
同样碰到这个问题

**Comment by TuiMao233** [comment]
在 1.8.2 中问题得到解决。
