### ISSUE TITLE
popup组建的customStyle不生效，好像加错位置了

### ISSUE THREAD

**Issue by qinkaiyuan** [YanxinNet/uView#64]
我想修改弹窗的圆角，最后发现改的是背景的圆角

![image](https://user-images.githubusercontent.com/14007972/83052101-6d1c0680-a081-11ea-8872-e6991553c5f5.png)
![image](https://user-images.githubusercontent.com/14007972/83052110-7016f700-a081-11ea-8dda-aa4c1e5821b9.png)
![image](https://user-images.githubusercontent.com/14007972/83052130-74dbab00-a081-11ea-9aa2-01b6952d7fa8.png)

**Comment by zhaocun6592** [comment]
自己加/deep/ button 修改样式吧。

**Comment by wangkaixuan0013** [comment]
popup弹窗的圆角请通过border-radius属性进行设置
