### ISSUE TITLE
u-field slot="button" button 不出来了，刚更新的

### ISSUE THREAD

**Issue by Adgeros** [YanxinNet/uView#66]
```
<u-field
                    label="验证码"
                    v-model="code"
                    type="number"
                    maxlength="6"
                    :field-style="{fontSize:'28rpx',color:'#252525'}"
                    placeholder="请输入验证码">
                    <u-button size="mini" slot="button" class='verify-btn' @tap="getCaptcha">{{tips}}</u-button>
                </u-field>
```

**Comment by windyflying** [comment]
文档有误，应该是slot="right"，看了源码，没有名称为`button`的插槽

**Comment by windyflying** [comment]
> ```
> <u-field
>                     label="验证码"
>                     v-model="code"
>                     type="number"
>                     maxlength="6"
>                     :field-style="{fontSize:'28rpx',color:'#252525'}"
>                     placeholder="请输入验证码">
>                     <u-button size="mini" slot="button" class='verify-btn' @tap="getCaptcha">{{tips}}</u-button>
>                 </u-field>
> ```

文档有误，应该是slot="right"，看了源码，没有名称为button的插槽

**Comment by Adgeros** [comment]
> > ```
> > <u-field
> >                     label="验证码"
> >                     v-model="code"
> >                     type="number"
> >                     maxlength="6"
> >                     :field-style="{fontSize:'28rpx',color:'#252525'}"
> >                     placeholder="请输入验证码">
> >                     <u-button size="mini" slot="button" class='verify-btn' @tap="getCaptcha">{{tips}}</u-button>
> >                 </u-field>
> > ```
> 
> 文档有误，应该是slot="right"，看了源码，没有名称为button的插槽

好哦
