### ISSUE TITLE
在main.js中引入会报错

### ISSUE THREAD

**Issue by Longder** [YanxinNet/uView#680]
报错信息：
Cannot read property 'mark' of undefined
去掉 import uView from "uview-ui" 
就不报错，但是这样的话就无法注册到全局的Vue中

**Comment by zbinf** [comment]
我也会这样

**Comment by Longder** [comment]
> 我也会这样

我发现是因为我用淘宝镜像源安装的uview-ui造成，如果是使用下载方式安装，就不会有这个问题

**Comment by Longder** [comment]
我还发现，如果是npm安装而非下载安装，配置了easycom之后，实际上组件里是已经可以直接使用了，并不用在main.js里import。但是实际小程序运行的时候，会报错，$u是undefined，那么就说明还是要Vue.use(uView)才行

**Comment by lincenying** [comment]
> 我还发现，如果是npm安装而非下载安装，配置了easycom之后，实际上组件里是已经可以直接使用了，并不用在main.js里import。但是实际小程序运行的时候，会报错，$u是undefined，那么就说明还是要Vue.use(uView)才行

这和什么方法装的没关系, 组件是独立的, 可以用easycom引入, 但是js的api必须要在main里use, 不然$u都没挂载到vue的原型链上去, 肯定报错

**Comment by Longder** [comment]
> > 我还发现，如果是npm安装而非下载安装，配置了easycom之后，实际上组件里是已经可以直接使用了，并不用在main.js里import。但是实际小程序运行的时候，会报错，$u是undefined，那么就说明还是要Vue.use(uView)才行
> 
> 这和什么方法装的没关系, 组件是独立的, 可以用easycom引入, 但是js的api必须要在main里use, 不然$u都没挂载到vue的原型链上去, 肯定报错
是的 但就是在main里import会报错
Cannot read property 'mark' of undefined

**Comment by lincenying** [comment]
把错误截个图看看, 我搜索源代码中就没有`mark`这个关键字

**Comment by Longder** [comment]
> 把错误截个图看看, 我搜索源代码中就没有`mark`这个关键字
![image](https://user-images.githubusercontent.com/7322594/101120454-a634c500-3628-11eb-910c-d83cb64c08ea.png)

**Comment by zbinf** [comment]
我找到了，在小程序开发者工具那边，吧es6转es5勾选去掉就不报错了

**Comment by Longder** [comment]
> 我找到了，在小程序开发者工具那边，吧es6转es5勾选去掉就不报错了

就是这个问题，解决了。不过还是用的淘宝镜像导入的yarn，不知道后续会有什么问题。感谢大神

**Comment by mangho** [comment]
> 我找到了，在小程序开发者工具那边，吧es6转es5勾选去掉就不报错了

mark 一个，也是同样的问题，解决了，感谢。

**Comment by sunxi1997** [comment]
同样遇到这个问题, 版本强制降到1.7.0可以解决, 小程序开发者工具取消勾选"es6转es5"也可以解决
