### ISSUE TITLE
请问scoped未来能取消掉吗，多好的UI库被限制样式修改好可惜

### ISSUE THREAD

**Issue by 79229788** [YanxinNet/uView#684]
这么好的UI库有点可惜，因为每个组件内部都开启了scoped，等同于封锁了自己的代码，但凡一家常用的第三方UI库，都不会开启scoped，因为一旦用了这个，组件样式在外部就无法在被修改了（因为生成的md5选择器权重覆盖不了），虽然作者提供了custom-style，但是没啥意义，不是所有模块都有custom-style，而且伪元素和伪类没法修改。而一个标准的UI库，使用者或多或少都会修改样式，是一定会修改一些细节样式来达到和自己产品的主题保持一致，所以一款常用的开源的组件库是一定不会使用scoped的，希望作者能考虑取消scoped，因为组件内部很多样式需要在组件外部用css进行调整修改，甚至全局修改。

**Comment by Venus-WXP** [comment]
取消scoped会污染全局样式，组件加scoped才是合理的选择，至于你想修改组件样式可以使用：
```scss
::v-deep {

   // 找到组件内部你想要调整的样式类，例如：
   .u-select {
       // 定义你自己样式即可
   }
}
```
希望可以帮到你！

**Comment by 79229788** [comment]
> 取消scoped会污染全局样式，组件加scoped才是合理的选择，至于你想修改组件样式可以使用：
> 
> ```css-scss
> ::v-deep {
> 
>    // 找到组件内部你想要调整的样式类，例如：
>    .u-select {
>        // 定义你自己样式即可
>    }
> }
> ```
> 
> 希望可以帮到你！



小程序不支持::v-deep吧，所以还是无法修改，你说的污染全局样式是指【被】全局污染吧，其实不会的，这个在定义classname的时候很重要， 所有组件内部className都应该规范性加前缀，细小的颗粒也需要加前缀，比如disabled, selected这类状态class名也要加前缀，比如u-disabled和u-selected。一旦这样做了后，被全局污染几率就会大大减少，被污染的仅仅只是标签选择器进行的样式修改，但是这种无法避免，因为或多或少属于使用者的用法不规范，使用者不可能在全局定义：div{xxxxxx},就算定义了也是项目本身一定需要的全局样式。vue里面的三方UI库随便说几个大牌UI，他们都不会加scoped，比如vue的饿了么UI库，有赞UI库这些都是使用率超高的库，他们永远不会启用scoped，不启用也是有道理的，因为使用率越多的库，越需要被定制化，一旦私有化封锁自己的库（特别是样式库），很多稍微有一丁点设计能力的公司或项目就无法使用，因为项目整体样式风格，哪怕是cell的高度，form项的高度都是有严格统一要求的，这些通常来说都是全局性的定义主题样式。

**Comment by mgbq** [comment]
/deep/可以修改的
