### ISSUE TITLE
唉，太多bug了吧，，NumberBox 步进器触发修改事件改变值后，居然重新赋值不行

### ISSUE THREAD

**Issue by bbzhengcheng** [YanxinNet/uView#69]
唉，太多bug了吧，，NumberBox 步进器触发修改事件改变值后，居然重新赋值不行

**Comment by YanxinNet** [comment]
不明白你这边说的问题，可以加QQ提供demo反馈问题：1042987248

**Comment by wangkaixuan0013** [comment]
1.3.3起，numberBox步进器推荐使用v-model双向绑定数值，无需在change回调中重新赋值
