### ISSUE TITLE
u-swipe-action 自动关闭无效

### ISSUE THREAD

**Issue by GalaxyNew** [YanxinNet/uView#70]
**能不能帮忙看看 怎么 list从接口获取数据后就无效了   按例子直接list赋值有用**

`<view>
			<u-toast ref="uToast"></u-toast>
			<u-swipe-action
				bg-color="rgb(250, 250, 250)"
				@open="open"
				:index="index"
				v-for="(item, index) in list"
				:key="item.id"
				:show="item.show"
				@click="click"
				:btn-width="btnWidth"
				:options="options"
				@content-click="contentClick"
			>
				<view class="item u-border-bottom">
					<u-row gutter="40">
						<u-col span="2" offset="1">
							<image mode="aspectFill" :src="item.headimgUrl" />
						</u-col>
						<u-col span="9" offset="0">
							<list>
								<view class="">
									<text class="title u-line-2">{{ item.userName }}</text>
								</view>
							</list>
							<list>
								<view class="">
									<u-icon name="star" :label="item.userPoints" color="#ff5500" label-color="#ff5500"></u-icon>
								</view>
							</list>
						</u-col>
					</u-row>
				</view>
			</u-swipe-action>

//获取用户列表
			getUserList(){
				api.yyUserPage(this.page)
				.then(res => {
					this.list = res.data.records
					for(var i = 0; i < this.list.length; i++){
						this.list[i].show = false;
					}
				})
			},

open(index) {
				// 先将正在被操作的swipeAction标记为打开状态，否则由于props的特性限制，
				// 原本为'false'，再次设置为'false'会无效
				this.list[index].show = true;
				this.list.map((val, idx) => {
					if(index != idx) this.list[idx].show = false;
				})
			},
`

**Comment by BeiQiaoT** [comment]
> 能不能帮忙看看 怎么 list从接口获取数据后就无效了 按例子直接list赋值有用
> 
> `
> 
> <u-swipe-action
> bg-color="rgb(250, 250, 250)"
> @OPEN="open"
> :index="index"
> v-for="(item, index) in list"
> :key="item.id"
> :show="item.show"
> @click="click"
> :btn-width="btnWidth"
> :options="options"
> @content-click="contentClick"
> >
> 
> 
> 
> 
> 
> 
> 
> 
> {{ item.userName }}
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> //获取用户列表
> getUserList(){
> api.yyUserPage(this.page)
> .then(res => {
> this.list = res.data.records
> for(var i = 0; i < this.list.length; i++){
> this.list[i].show = false;
> }
> })
> },
> 
> open(index) {
> // 先将正在被操作的swipeAction标记为打开状态，否则由于props的特性限制，
> // 原本为'false'，再次设置为'false'会无效
> this.list[index].show = true;
> this.list.map((val, idx) => {
> if(index != idx) this.list[idx].show = false;
> })
> },
> `

我这边是没问题的，请问您现在解决了吗

**Comment by buildJava** [comment]
采用同样的方法不生效，发现组件内部的show值不变，另外单一打开同一个是否可以做成默认动作呢，因为在大多数场景下，都是操作完一个再操作另一个

**Comment by BeiQiaoT** [comment]
> 采用同样的方法不生效，发现组件内部的show值不变，另外单一打开同一个是否可以做成默认动作呢，因为在大多数场景下，都是操作完一个再操作另一个

emm。。我不是很明白你的意思，能说的详细一些吗

**Comment by buildJava** [comment]
> > 采用同样的方法不生效，发现组件内部的show值不变，另外单一打开同一个是否可以做成默认动作呢，因为在大多数场景下，都是操作完一个再操作另一个
> 
> emm。。我不是很明白你的意思，能说的详细一些吗

你好，使用网站上提供的方式,【打开一个swipeAction的同时，需要自动关闭其他的swipeAction】同样的方法发现不起作用，通过控制台vue组件查看show的值，发现值不发生变化。

另外在平时的使用场景下，应该都是打开一个，自动关闭另外一个，这个是否可以做成默认动作呢，或者提供一个配置方法，选择开启或者不开启这种展示形式，使用起来更加方便。
感谢作者的辛苦付出。

**Comment by tttao7** [comment]
@buildJava 吓得我赶紧去看了下示例项目 是自动关闭的哈 你可以参考下uView官网示例http://uviewui.com/components/swipeAction.html

**Comment by tttao7** [comment]
完整示例项目在这 https://ext.dcloud.net.cn/plugin?id=1593

**Comment by buildJava** [comment]
> @buildJava 吓得我赶紧去看了下示例项目 是自动关闭的哈 你可以参考下uView官网示例http://uviewui.com/components/swipeAction.html

我的意思是组件默认实现就是自动关闭另外一个，不需要实现@open事件响应，完全模仿写法，发现还是不行，看来还是我的姿势不对

**Comment by buildJava** [comment]
> 完整示例项目在这 https://ext.dcloud.net.cn/plugin?id=1593

另外在做业务需求时发现有么几个点，作者大大可以看看是否需要合并至项目中：
1.u-navbar.vue文件，标题的字体粗细定义
2.u-avatar.vue文件头像增加边框
3.timeFrom.js文件中timeFrom方法，当年，只显示XX月XX日
4.colorGradient.js文件hexToRgb方法增加opacity透明度设置的参数

**Comment by EDGDK** [comment]
我也碰到了这种情况 根据后端返回数据自动关闭无效 楼上怎么解决的

**Comment by EDGDK** [comment]
> 完整示例项目在这 https://ext.dcloud.net.cn/plugin?id=1593

我也碰到了这种情况 根据后端返回数据自动关闭无效 楼上怎么解决的

**Comment by gd4Ark** [comment]
@EDGDK 临时 HACK 方案：https://github.com/YanxinNet/uView/issues/761

**Comment by MroZ11** [comment]
使用Vue.set 设置show字段 ，不要直接赋值

**Comment by EDGDK** [comment]
> 使用Vue.set 设置show字段 ，不要直接赋值

set赋值也试过了，还是无效
