### ISSUE TITLE
1.2.9更新后request响应拦截器return false失效，请求无法进入catch

### ISSUE THREAD

**Issue by uu109** [YanxinNet/uView#71]
目前bug感觉还不少，作者维护着吃力不，需要帮忙的话我可以添一分力

**Comment by BeiQiaoT** [comment]
> 目前bug感觉还不少，作者维护着吃力不，需要帮忙的话我可以添一分力

这个问题已经记录

**Comment by Tangdouba** [comment]
在uview-ui/libs/request/index.js 文件中去掉.catch(e => {}) 上传更新加的无用代码 catch了还什么都不处理不是指定啥意思 哎
