### ISSUE TITLE
Line 线条组件 hair-line="true" hair-line="false"设置后属性无差别

### ISSUE THREAD

**Issue by JuliusDeng** [YanxinNet/uView#72]
![image](https://user-images.githubusercontent.com/43316733/83318544-83d08200-a268-11ea-98e1-7882d07e4013.png)
hair-line属性设置true或者false之后显示都是一样的 感觉显示的都是细边  求解

**Comment by BeiQiaoT** [comment]
> ![image](https://user-images.githubusercontent.com/43316733/83318544-83d08200-a268-11ea-98e1-7882d07e4013.png)
> hair-line属性设置true或者false之后显示都是一样的 感觉显示的都是细边 求解

:hair-line="true" 这样使用哦，前面加上冒号

**Comment by JuliusDeng** [comment]
en&nbsp; 好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BeiQiaoT"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月30日(星期六) 晚上8:28
收件人:&nbsp;"YanxinNet/uView"<uView@noreply.github.com&gt;;
抄送:&nbsp;"起风了"<1576554007@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YanxinNet/uView] Line 线条组件 hair-line="true" hair-line="false"设置后属性无差别 (#72)





  

 hair-line属性设置true或者false之后显示都是一样的 感觉显示的都是细边 求解
  
:hair-line="true" 这样使用哦，前面加上冒号
