### ISSUE TITLE
Sticky 吸顶全面屏适配问题

### ISSUE THREAD

**Issue by maikro-v** [YanxinNet/uView#727]
自定义导航栏时，Sticky组件的offset-top如何设置才能吸附到自定义导航栏下方

**Comment by maikro-v** [comment]
全面屏与非全面屏的statusBarHeight高度不一样，需要如何处理

**Comment by DogBrown** [comment]
> 全面屏与非全面屏的statusBarHeight高度不一样，需要如何处理

可以动态计算状态栏高度 再加上自定义导航栏的高度 就是吸顶便宜距离
