### ISSUE TITLE
uView一人才管理员骂人！

### ISSUE THREAD

**Issue by Bruce-7** [YanxinNet/uView#754]
因为接触比较少网页开发。就看了uniapp官网的信息。也自己查询了百度很多信息。
自己也不是一个张口就问的人，也会自己通过查看信息和资料。
举例其中几个：
https://segmentfault.com/a/1190000037528477
https://uniapp.dcloud.net.cn/adapt
hello uni-app：https://hellouniapp.dcloud.net.cn/

自己也不是很确定可否这样进行，然后就在uView（官方2群： 249718512）官方群提问一句原话：”有大佬用uniapp+uView开发pc网站的吗？还是建议直接vue+element?“。
其中一个管理员就骂人，我就回应了一句：”你可以不回答，但是不应该骂人“。又骂了一句把我踢了！
这样的人居然能在uView当管理员！真心让人不悦！我也不想骂人。这个人才管理员自己以为自己了不起完了。
真心不如uniapp官方群的朋友。真是心态和素质决定一个人的一生！

![image](https://user-images.githubusercontent.com/12136869/103518190-45f6a480-4eae-11eb-9342-235f09364434.png)

**Comment by isaxiao** [comment]
案发现场已了解，对于此类不愉快的事情我们深感抱歉，也欢迎你继续使用uview，uniapp虽然支持pc端，但毕竟不是一个pc框架，uview目前计划局限于移动端，后期可能会支持uniapppc端，uview4群和5群欢迎你的到来和提问。

**Comment by 121132839** [comment]
哈哈哈
