### ISSUE TITLE
u-no-network 导致微信小程序自定义navigationBar失效

### ISSUE THREAD

**Issue by bugstark** [YanxinNet/uView#76]
u-no-network 组件有
mounted() {
			uni.setNavigationBarColor({
			    frontColor: '#000000',
			    backgroundColor: '#ffffff',
			})
}
覆盖了globalStyle的设置

**Comment by BeiQiaoT** [comment]
> u-no-network 组件有
> mounted() {
> uni.setNavigationBarColor({
> frontColor: '#000000',
> backgroundColor: '#ffffff',
> })
> }
> 覆盖了globalStyle的设置

收到

**Comment by YanxinNet** [comment]
1.3.0版本已移除此部分代码，感谢反馈！
