### ISSUE TITLE
u-rate组件在h5端显示正常 微信小程序中不显示 组件未设置其它特殊属性

### ISSUE THREAD

**Issue by BecksWang** [YanxinNet/uView#769]
<u-rate  count="count" :disabled="true"  v-model="rate"></u-rate> 这是我使用的方法 rate:10, count:5,

**Comment by BecksWang** [comment]
<u-rate  count="count" :disabled="true"  v-model="rate"></u-rate>

**Comment by BecksWang** [comment]
u-rate count=“count” :disable="true" v-model="rate"

**Comment by whypretender** [comment]
我也遇到一样的问题

**Comment by BecksWang** [comment]
> 我也遇到一样的问题， 刚才对比了很早之前下载的uview 之前的是可以用的， 对比代码u-rate组件文件修改过，修改处问题了？

u-rate  :disabled="true" value="5" u-rate 你这样用 用value 不用rate 和count

**Comment by BecksWang** [comment]
u-rate :disabled="true" value="5" u-rate 用value 不用rate 和count 这样可以显示
