### ISSUE TITLE
打包后的文件太大了，每个组件都有一个60多K的wxss文件，但是都是一样的内容

### ISSUE THREAD

**Issue by lxiaosky** [YanxinNet/uView#79]
按照教程使用easycom引入，最后一共使用了12个组件，打包出来的文件，光是uview文件夹就有900多K，查看文件发现每个文件下都有一个60多K的wxss，因为加了因为加了scoped，所以里面很多样式都是公共样式，只是样式作用域不同，在微信小程序里面特别紧张，这个问题能解决下么，把公共的样式单独放一个文件，减小每个文件的体积

**Comment by BeiQiaoT** [comment]
> 按照教程使用easycom引入，最后一共使用了12个组件，打包出来的文件，光是uview文件夹就有900多K，查看文件发现每个文件下都有一个60多K的wxss，因为加了因为加了scoped，所以里面很多样式都是公共样式，只是样式作用域不同，在微信小程序里面特别紧张，这个问题能解决下么，把公共的样式单独放一个文件，减小每个文件的体积

您使用的是哪个版本的呢？之前是有一个版本微型小程序打包css文件过大的问题，新版本已经修复

**Comment by lxiaosky** [comment]
目前使用的是1.2.8版本

**Comment by yuzmb** [comment]
变量css放到uni.scss，其他的css放到app.vue引入

**Comment by lxiaosky** [comment]
好的

**Comment by lxiaosky** [comment]
![331](https://user-images.githubusercontent.com/26298325/83387409-43673480-a41f-11ea-91ab-ba8f5d5f191a.png)
![3312](https://user-images.githubusercontent.com/26298325/83387613-95a85580-a41f-11ea-9a19-ac8056f7b103.png)
在uni.scss引入的uview的index.scss文件，打包微信小程序之后，会有一个单独的uview文件夹，里面的每个组件的wxss文件都有3000多行，60多k的大小

**Comment by remember-5** [comment]
遇到同样的问题，请问问题解决了吗 @lxiaosky
