### ISSUE TITLE
[bug] 关于Sticky 组件 报 Uncaught TypeError: Cannot read property 'bottom' of null

### ISSUE THREAD

**Issue by kimpyoon** [YanxinNet/uView#8]
切换组件时 报了这个错误，日志定位不了代码行，虽然不影响使用，也希望解决一下

**Comment by xiaokonglongya** [comment]
> 切换组件时 报了这个错误，日志定位不了代码行，虽然不影响使用，也希望解决一下

具体实在那个端运行的？

**Comment by kimpyoon** [comment]
> > 切换组件时 报了这个错误，日志定位不了代码行，虽然不影响使用，也希望解决一下
> 
> 具体实在那个端运行的？

h5
