### ISSUE TITLE
关于u-field右侧插槽命名错误

### ISSUE THREAD

**Issue by mentoorliubin** [YanxinNet/uView#80]
u-field右侧插槽命名应该是right不是button,麻烦修改下文档

**Comment by BeiQiaoT** [comment]
> u-field右侧插槽命名应该是right不是button,麻烦修改下文档

官方文档是right呀

**Comment by mentoorliubin** [comment]
> > u-field右侧插槽命名应该是right不是button,麻烦修改下文档
> 
> 官方文档是right呀

![image](https://user-images.githubusercontent.com/52729282/83380172-def0a900-a40f-11ea-96bf-5b6157b9db38.png)

**Comment by BeiQiaoT** [comment]
> > > u-field右侧插槽命名应该是right不是button,麻烦修改下文档
> > 
> > 
> > 官方文档是right呀
> 
> ![image](https://user-images.githubusercontent.com/52729282/83380172-def0a900-a40f-11ea-96bf-5b6157b9db38.png)

这个源码是没来得及改，已经记录

**Comment by YanxinNet** [comment]
1.3.0版本已修改文档，感谢反馈
