### ISSUE TITLE
BUG: http模块中配置合并问题

### ISSUE THREAD

**Issue by 2460392754** [YanxinNet/uView#83]
http模块使用了`Object.assign`进行合并数据，这样会导致没法深合并数据，只能浅合并(类似于浅拷贝)。

例如模块中默认配置的`this.config`里的`header`对象，在`setConfig`中再次添加`header`进行数据合并，就会导致默认的`header`数据丢失。

例如: 
``` js
const defaultConfig = {
	header: {
		"content-type": "application/json;charset=UTF-8",
	},
};

const myConfig = {
	header: {
		appId: 1,
	},
};

Object.assign(defaultConfig, myConfig); // { header: { appid: 1 } }

```

**Comment by 2460392754** [comment]
[uView http模块](https://github.com/YanxinNet/uView/blob/master/uview-ui/libs/request/index.js#L9-L28)

**Comment by YanxinNet** [comment]
感谢反馈，Object.assign()为浅拷贝，已通过深拷贝办法修复了此问题。
