### ISSUE TITLE
Syntax Error: SassError: Undefined variable.

### ISSUE THREAD

**Issue by buqiyuan** [YanxinNet/uView#838]
![image](https://user-images.githubusercontent.com/39730999/108730951-03288300-7567-11eb-82c6-669d25dc48f0.png)

![image](https://user-images.githubusercontent.com/39730999/108732275-60710400-7568-11eb-8372-e59353d9981d.png)
该装的都装了，配置也是按照官网npm方式配的，该重启的也重启了，还是有很多用到这些scss变量的组件不能使用

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/108733068-1b010680-7569-11eb-8f44-da09b9119e3c.png)
SwipeAction这些组件是正常的，就sass变量那里不知啥问题，手动复制UView的主题变量到uni.scss里面都不生效。
代码地址：https://github.com/buqiyuan/uni-chat

**Comment by Caffeine19** [comment]
请问你的uview，sass，sass-loader版本是？到底应该安装node-sass还是sass
