### ISSUE TITLE
tabsSwiper 全屏选项卡点击Tabs移动距离有误

### ISSUE THREAD

**Issue by xiaojiangK** [YanxinNet/uView#839]
tabsSwiper 全屏选项卡点击Tabs移动距离有误

问题：
点击第一屏后面的TAB，TABS整体会移动到前面，然后再弹回原位置，体验非常不好

线上地址：https://m.vodeshop.com/o2o/

![image](https://user-images.githubusercontent.com/30304529/109098820-f40b2600-775c-11eb-9389-01d9395fba72.png)

**Comment by wangmeng1991** [comment]
@xiaojiangK 一样的问题 请问是怎么解决的
