### ISSUE TITLE
u-switch 组件 @change 事件的一个bug

### ISSUE THREAD

**Issue by xhb** [YanxinNet/uView#84]
![image](https://user-images.githubusercontent.com/3167082/83443655-adfa8d80-a47c-11ea-8dba-f2a6f088e8eb.png)

**Comment by xhb** [comment]
this 指向问题，请大佬修改一下。

**Comment by BeiQiaoT** [comment]
> this 指向问题，请大佬修改一下。

收到

**Comment by Tokinx** [comment]
这不是bug。请使用箭头函数。

**Comment by YanxinNet** [comment]
已修改此问题，感谢反馈
