### ISSUE TITLE
tabsSwipe+自定义导航栏，到底部的时候，选项卡会隐藏

### ISSUE THREAD

**Issue by anylys** [YanxinNet/uView#88]
tabsSwipe+自定义导航栏，到底部的时候，选项卡会隐藏
用的是订单列表的改造的

**Comment by anylys** [comment]
目前解决方案：<u-tabs-swiper style="position: fixed;" ......

**Comment by YanxinNet** [comment]
请参考演示项目，此tabsSwiper组件需要结合swiper和scroll-view才能发挥作用，可以通过calc(100% - var(--window-top))类似的形式定义swiper的高度，内部通过scroll-view进行滚动，同时监听scroll-view的触底事件进行加载更多，具体做法请参考：
https://www.uviewui.com/components/tabsSwiper.html
下载演示项目即可查看源码：
https://download.uviewui.com/uView_1.3.2_demo.zip
