### ISSUE TITLE
导入错误

### ISSUE THREAD

**Issue by dancing-monkey** [YanxinNet/uView#9]
快速上手中的3
```
/* uni.scss */
@import "uview-ui/themb.scss";
```
应修改为
```
/* uni.scss */
@import "uview-ui/theme.scss";
```

**Comment by BeiQiaoT** [comment]
> 快速上手中的3
> 
> ```
> /* uni.scss */
> @import "uview-ui/themb.scss";
> ```
> 
> 应修改为
> 
> ```
> /* uni.scss */
> @import "uview-ui/theme.scss";
> ```

已修正
