### ISSUE TITLE
大佬，这个可以整不：打包需要去掉没有用到数据。小程序，珍惜文件大小~

### ISSUE THREAD

**Issue by anihCevol** [YanxinNet/uView#90]
打包去掉没有用到的数据。目前看到的代码，打包但没有用到的有：picker的省市区三个文件，和empty ，icon.js。大佬，这个可以整不。

**Comment by BeiQiaoT** [comment]
> 打包去掉没有用到的数据。目前看到的代码，打包但没有用到的有：picker的省市区三个文件，和empty ，icon.js。大佬，这个可以整不。

这个正在考虑优化
