### ISSUE TITLE
city-select 城市选择组件列表滚动不了

### ISSUE THREAD

**Issue by FreeTrea** [YanxinNet/uView#92]
h5，小程序都滚动不了。小程序初始化全部打勾

**Comment by BeiQiaoT** [comment]
> h5，小程序都滚动不了。小程序初始化全部打勾

是有这个问题，这是uview一个使用者提供的模版，当时他给了错误的测试版本，导致了这个问题，下面会修改

**Comment by wangkaixuan0013** [comment]
此问题已在1.3.3版本修复
