### ISSUE TITLE
关于组件：ReadMore 展开阅读更多

### ISSUE THREAD

**Issue by fuyunmanbu** [YanxinNet/uView#93]
在有些场景中，我并不需要自动空格，能不能取消或者使用其他方式管理？
![Snip20200603_2](https://user-images.githubusercontent.com/16368126/83608727-e18a0480-a5af-11ea-8bc9-65ad10a17246.png)

```
.u-content {
	font-size: 30rpx;
	color: $u-content-color;
	line-height: 1.8;
	text-align: left;
	text-indent: 2em; //这里
	overflow: hidden;
}
```

**Comment by BeiQiaoT** [comment]
> 在有些场景中，我并不需要自动空格，能不能取消或者使用其他方式管理？
> ![Snip20200603_2](https://user-images.githubusercontent.com/16368126/83608727-e18a0480-a5af-11ea-8bc9-65ad10a17246.png)
> 
> ```
> .u-content {
> 	font-size: 30rpx;
> 	color: $u-content-color;
> 	line-height: 1.8;
> 	text-align: left;
> 	text-indent: 2em; //这里
> 	overflow: hidden;
> }
> ```

好的，收到此建议

**Comment by tttao7** [comment]
您也可以使用deep进行css修改 感谢您的建议
