### ISSUE TITLE
u-count-down 时间未补零bug

### ISSUE THREAD

**Issue by mentoorliubin** [YanxinNet/uView#95]
![image](https://user-images.githubusercontent.com/52729282/83619588-a8a55c00-a5be-11ea-8993-a804ad9cef4d.png)
此处进行了补零操作，但是并没有进行对应的正确赋值

**Comment by BeiQiaoT** [comment]
> ![image](https://user-images.githubusercontent.com/52729282/83619588-a8a55c00-a5be-11ea-8993-a804ad9cef4d.png)
> 此处进行了补零操作，但是并没有进行对应的正确赋值

好的，收到

**Comment by YanxinNet** [comment]
1.3.0版本已处理此问题，感谢反馈
