### ISSUE TITLE
u-fileld 在button位置插入u-button不显示

### ISSUE THREAD

**Issue by rongwei84n** [YanxinNet/uView#96]
按照下面例子里面敲的，发现尾部并没有出现u-button按钮。
https://www.uviewui.com/components/field.html

<template>
    <view class="">
        <u-cell-group>
            <u-field
                v-model="code"
                label="验证码"
                placeholder="请填写验证码"
            >
                <u-button size="mini" slot="button" type="success" @tap="getCode">{{codeText}}</u-button>
            </u-field>
            <u-verification-code ref="uCode" @change="codeChange"></u-verification-code>
        </u-cell-group>
		</view>
</template>
<script>
    export default {
        data() {
            return {
                mobile: '',
                code: '',
                codeText: '验证码'
            }
        },
        methods: {
            codeChange(text) {
                this.codeText = text;
            },
            getCode() {
                if(this.$refs.uCode.canGetCode) {
                    // 模拟向后端请求验证码
                    uni.showLoading({
                        title: '正在获取验证码'
                    })
                    setTimeout(() => {
                        uni.hideLoading();
                        // 通知验证码组件内部开始倒计时
                        this.$refs.uCode.start();
                    }, 1000);
                }else {
                    this.$u.toast('倒计时结束后再发送');
                }
            }
        }
    }
</script>

**Comment by BeiQiaoT** [comment]
> 按照下面例子里面敲的，发现尾部并没有出现u-button按钮。
> https://www.uviewui.com/components/field.html
> 
> {{codeText}} <script> export default { data() { return { mobile: '', code: '', codeText: '验证码' } }, methods: { codeChange(text) { this.codeText = text; }, getCode() { if(this.$refs.uCode.canGetCode) { // 模拟向后端请求验证码 uni.showLoading({ title: '正在获取验证码' }) setTimeout(() => { uni.hideLoading(); // 通知验证码组件内部开始倒计时 this.$refs.uCode.start(); }, 1000); }else { this.$u.toast('倒计时结束后再发送'); } } } } </script>

官方api修改了，改成slot = “right”

**Comment by rongwei84n** [comment]
确实改成right就可以了，非常感谢！🙏
