### ISSUE TITLE
主题色修改问题

### ISSUE THREAD

**Issue by zhonghangAlex** [YanxinNet/uView#98]
您好请问我希望修改组件的主题色，可是在theme.scss修改了，引入什么的都是正确的，可是为什么主题色还是蓝色（重启过了）？？？

**Comment by BeiQiaoT** [comment]
> 您好请问我希望修改组件的主题色，可是在theme.scss修改了，引入什么的都是正确的，可是为什么主题色还是蓝色（重启过了）？？？

目前颜色配置比较复杂，后续版本会出主题的配置

**Comment by wangkaixuan0013** [comment]
1.4.0版本开始已支持自定义主题https://www.uviewui.com/guide/theme.html
