### ISSUE TITLE
文档更新

### ISSUE THREAD

**Issue by kmq116** [YanxinNet/uView#995]
input 组件的 blur 事件，代码中是有回调的，但是文档中没有写

**Comment by Zebra-web** [comment]
> input 组件的 blur 事件，代码中是有回调的，但是文档中没有写

有些组件的功能根本就没有实例代码，比如卡片的阴影属性就没有，也不知道怎么用

**Comment by kmq116** [comment]
所以使用起来要经常去源码里瞧一眼，挺痛苦的
